"""意味モデル → ADK プロジェクトのソース（要件書 §3.1 / §3.2 / §3.3）。

**このモジュールは `google.adk` を import しない。** 生成するのはテキストであって
ADK オブジェクトではないので、`jin build` に ADK のロード（数秒かかる）を強いる理由が無い。
引数名の正しさは `packages/jin-adk/tests/test_adk_surface.py` が実物の
`google-adk` 2.8.0 に対して固定する（記憶で書かない・`adk-api-probe.md`）。

## 生成物が `jin` に依存しないこと（ADR-008 / DP-JIN-CODEGEN-RUNTIME-01 案 A）

`flow.exit` の判定エージェント `StateCheckAgent` の**クラス本体を毎回埋め込む**。
要件書 §3.1 が `adk run <out>/<root_name>` と `adk web <out>` で「そのまま動く」ことを
要求するので、生成プロジェクトの実行に `jin` のインストールを要求してはならない。
`FakeLlm` は `jin run --model fake` が実行時に差し替えるものであって生成物の一部ではないため、
`jin_adk` 側（`jin_adk.fake_llm`）に置く。

## 決定性（NFR-DET-002 と同じ厳しさで扱う）

同じモデルからは**バイト単位で同じ** `agent.py` が出る。並びはすべてモデルの配列順か、
モデルから決まる位相順で決める。`set` の反復順や辞書のハッシュ順に依存しない。
"""

from __future__ import annotations

import json
import keyword
from dataclasses import dataclass

from jin_core.model import Circle, JinFile, ToolBuiltin, ToolFunction, ToolSummon
from jin_core.pointer import join
from jin_core.resolver import check_ref_format

from jin_adk.errors import CompileError, CompileIssue
from jin_adk.pointers import PointerMap

#: 生成物の 1 行目。要件書 §3.2 の文言をそのまま使う。
HEADER = "# generated by jin — do not edit"

#: `google.adk.tools` が**インスタンスとして**公開している組み込みツール（google-adk 2.8.0 実測）。
#: クラスではないので `tools=[...]` にそのまま置く（`docs/spec/adk-mapping.md` §2.2）。
#: ここに無い `builtin` はコンパイル時エラーにする。黙って落とさない（NFR-FAIL-001）。
#: **この定数が実物とずれていないことは `tests/test_adk_surface.py` が実測で落とす。**
BUILTIN_TOOLS: tuple[str, ...] = (
    "enterprise_web_search",
    "get_user_choice",
    "google_maps_grounding",
    "google_search",
    "load_artifacts",
    "load_memory",
    "preload_memory",
    "request_input",
    "url_context",
)

#: `flow.exit` の判定エージェントの名前を circle 名から作る接尾辞。
EXIT_AGENT_SUFFIX = "__exit"

#: 生成モジュールが公開するエントリポイント（要件書 §2.1「root → 生成モジュールの root_agent」）。
ROOT_VARIABLE = "root_agent"

#: 生成コードが自分で使う名前。ユーザ由来の名前がここに衝突したら別名を付ける。
_RESERVED_NAMES = frozenset(
    {
        ROOT_VARIABLE,
        "StateCheckAgent",
        "Any",
        "AsyncGenerator",
        "BaseAgent",
        "LlmAgent",
        "LoopAgent",
        "ParallelAgent",
        "SequentialAgent",
        "InvocationContext",
        "Event",
        "EventActions",
        "AgentTool",
        "FunctionTool",
        "LongRunningFunctionTool",
        *BUILTIN_TOOLS,
    }
)

#: ADK が予約している agent 名（実測: `BaseAgent.validate_name`）。
_ADK_RESERVED_AGENT_NAMES = frozenset({"user"})

#: `guards[].on` のうち LlmAgent にしか無いもの（実測: workflow agent の model_fields）。
_LLM_ONLY_GUARD_ONS = frozenset({"before_model", "after_model", "before_tool", "after_tool"})

#: 埋め込む判定エージェント（ADR-008 案 A）。`BaseAgent._run_async_impl` を override する。
#: 条件が成立したときだけ `EventActions(escalate=True)` を出す（要件書 §3.3）。
_STATE_CHECK_AGENT = '''class StateCheckAgent(BaseAgent):
    """flow.exit の判定。条件が成立したら escalate して LoopAgent を抜ける。"""

    state_key: str
    expected: Any

    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        if ctx.session.state.get(self.state_key) == self.expected:
            yield Event(author=self.name, actions=EventActions(escalate=True))
'''


def _py_string(text: str) -> str:
    """Python の文字列リテラルにする。

    改行を含み、かつ素直に三重引用符へ入れられるものだけ三重引用符にする
    （要件書 §3.2 の `instruction=\"\"\"...\"\"\"` の形）。それ以外は
    `json.dumps` のエスケープを使う。JSON の文字列エスケープは Python の文字列
    リテラルとして**そのまま妥当**であり（`\\"` / `\\\\` / `\\n` / `\\uXXXX`）、
    `ensure_ascii=False` で非 ASCII をエスケープしないので正準形の方針とも揃う。
    """
    if "\n" in text and "\\" not in text and '"""' not in text and not text.endswith('"'):
        return f'"""{text}"""'
    return json.dumps(text, ensure_ascii=False)


def _module_alias(ref: str) -> str:
    """`research.tools:publish` → `research_tools__publish`（衝突時の別名）。"""
    module, _, name = ref.partition(":")
    return f"{module.replace('.', '_')}__{name}"


@dataclass(frozen=True, slots=True)
class GeneratedProject:
    """`jin build` が書き出すものと、`jin run` が実行時に使うもの。

    `pointer_map` は**生成物には書き出さない**（ADR-009 / 要件書 §3.1 の 3 ファイル）。
    """

    root_name: str
    agent_py: str
    init_py: str
    env_example: str
    pointer_map: PointerMap


class _Generator:
    """1 モデル分の生成。状態を持つので関数ではなくクラスにする。"""

    def __init__(self, model: JinFile) -> None:
        self.model = model
        self.issues: list[CompileIssue] = []
        self.by_name: dict[str, Circle] = {c.name: c for c in model.circles}
        self.index_of: dict[str, int] = {c.name: i for i, c in enumerate(model.circles)}
        self.pointers = PointerMap()
        #: circle 名 → 生成コード上の変数名。
        self.variable: dict[str, str] = {}
        #: `module:callable` → 生成コード上のローカル名。
        self.local_name: dict[str, str] = {}
        #: import を出す順（モジュール first-appearance 順、その中で名前 first-appearance 順）。
        self.import_order: list[str] = []

    # -- 検査 -------------------------------------------------------------------------
    def _fail(self, pointer: str, message: str, hint: str) -> None:
        self.issues.append(CompileIssue(pointer=pointer, message=message, hint=hint))

    def _circle_pointer(self, name: str) -> str:
        return join(join("", "circles"), self.index_of[name])

    def _check_names(self) -> None:
        """circle 名が ADK の agent 名として使えることを見る（実測の制約）。

        `BaseAgent.validate_name` は `str.isidentifier()` を要求し、`user` を拒む。
        Jin の `name` は制御文字以外なら何でも通るので、ここが最初の関門になる。
        """
        for name in self.by_name:
            pointer = join(self._circle_pointer(name), "name")
            if not name.isidentifier() or keyword.iskeyword(name):
                self._fail(
                    pointer,
                    f"circle 名 '{name}' は ADK の agent 名にできません"
                    "（Python の識別子である必要があります）",
                    "英字かアンダースコアで始まり、英数字とアンダースコアだけからなる名前"
                    "（例: Summarizer / step_1）に rename してください",
                )
            elif name in _ADK_RESERVED_AGENT_NAMES:
                self._fail(
                    pointer,
                    f"circle 名 '{name}' は ADK が予約しています"
                    "（エンドユーザの入力を指す名前です）",
                    f"'{name}' 以外の名前へ rename してください",
                )

    def _check_circle_shape(self, circle: Circle) -> None:
        """核なし circle（workflow agent）に写せないキーが無いかを見る。

        `SequentialAgent` / `ParallelAgent` / `LoopAgent` の `model_fields` には
        `instruction` / `tools` / `output_key` が**存在しない**（実測）。
        黙って落とすと「書いたのに効かない」になるのでコンパイル時に落とす。
        """
        base = self._circle_pointer(circle.name)
        outs = [i for i, state in enumerate(circle.state) if state.out]
        if len(outs) > 1:
            names = " / ".join(circle.state[i].name for i in outs)
            self._fail(
                join(base, "state"),
                f"circle '{circle.name}' に out: true の state が {len(outs)} 件あります"
                f"（{names}）。LlmAgent.output_key は 1 つしか取れません",
                "1 件だけ out: true にし、残りはサブ陣（summon する別 circle）へ分けてください",
            )
        if circle.flow is None:
            return
        kind = circle.flow.kind
        if circle.instruction is not None:
            self._fail(
                join(base, "instruction"),
                f"核なし circle '{circle.name}'（flow.kind: {kind}）に instruction は写せません",
                "instruction は核あり circle（core を持つ LlmAgent）にだけ書けます。"
                "指示を持つサブ陣を作り flow.steps に並べてください",
            )
        if circle.tools:
            self._fail(
                join(base, "tools"),
                f"核なし circle '{circle.name}'（flow.kind: {kind}）に tools は写せません",
                "tools を持つサブ陣（core を持つ circle）を作り flow.steps に並べてください",
            )
        if circle.delegate:
            self._fail(
                join(base, "delegate"),
                f"核なし circle '{circle.name}'（flow.kind: {kind}）に delegate は写せません"
                "（sub_agents は flow.steps が使います）",
                "委譲は核あり circle にだけ書けます。flow.steps に並べるか、"
                "delegate を持つサブ陣を作ってください",
            )
        if outs:
            self._fail(
                join(join(base, "state"), outs[0]),
                f"核なし circle '{circle.name}'（flow.kind: {kind}）の state に out: true は写せません"
                "（workflow agent に output_key はありません）",
                "out: true は核あり circle の state に付けてください",
            )
        for i, guard in enumerate(circle.boundary.guards if circle.boundary else []):
            if guard.on in _LLM_ONLY_GUARD_ONS:
                self._fail(
                    join(join(join(base, "boundary"), "guards"), i),
                    f"核なし circle '{circle.name}'（flow.kind: {kind}）に "
                    f"'{guard.on}' のコールバックは写せません",
                    "workflow agent が持つのは before_agent / after_agent だけです。"
                    f"'{guard.on}' は核あり circle の boundary に移してください",
                )

    def _check_refs_and_builtins(self, circle: Circle) -> None:
        base = self._circle_pointer(circle.name)
        awaited = set(circle.boundary.await_) if circle.boundary else set()
        for i, tool in enumerate(circle.tools):
            pointer = join(join(base, "tools"), i)
            if isinstance(tool, ToolFunction):
                reason = check_ref_format(tool.ref)
                if reason is not None:
                    self._fail(
                        join(pointer, "ref"),
                        f"Python 参照 '{tool.ref}' から import 文を作れません（{reason}）",
                        "module.path:callable の形（例: research.tools:web_search）で書いてください",
                    )
            elif isinstance(tool, ToolBuiltin) and tool.builtin not in BUILTIN_TOOLS:
                self._fail(
                    join(pointer, "builtin"),
                    f"組み込みツール '{tool.builtin}' は google-adk 2.8.0 にありません",
                    "次のいずれかに書き換えてください: " + " / ".join(BUILTIN_TOOLS),
                )
            if tool.name in awaited and not isinstance(tool, ToolFunction):
                self._fail(
                    pointer,
                    f"await 対象の tool '{tool.name}' は kind: {tool.kind} なので "
                    "LongRunningFunctionTool にできません",
                    "boundary.await に書けるのは kind: tool（Python の関数）だけです。"
                    f"'{tool.name}' を await から外してください",
                )
        for i, guard in enumerate(circle.boundary.guards if circle.boundary else []):
            reason = check_ref_format(guard.ref)
            if reason is not None:
                self._fail(
                    join(join(join(base, "boundary"), "guards"), i) + "/ref",
                    f"Python 参照 '{guard.ref}' から import 文を作れません（{reason}）",
                    "module.path:callable の形（例: research.guards:pii_filter）で書いてください",
                )

    # -- 名前の割り当て ----------------------------------------------------------------
    def _assign_variables(self) -> None:
        """circle → 生成コード上の変数名。root だけ `root_agent` になる。

        root 以外の circle が `root_agent` という名前だと、生成コードの中で
        エントリポイントと衝突する。rename を促す（黙って別名にすると、
        利用者が読んだ生成コードと `.jin` の名前が食い違う）。
        """
        for circle in self.model.circles:
            if circle.name == self.model.root:
                self.variable[circle.name] = ROOT_VARIABLE
                continue
            if circle.name == ROOT_VARIABLE:
                self._fail(
                    join(self._circle_pointer(circle.name), "name"),
                    f"circle 名 '{ROOT_VARIABLE}' は生成モジュールのエントリポイント名と衝突します",
                    f"root ではない circle に '{ROOT_VARIABLE}' という名前は使えません。"
                    "rename してください",
                )
            self.variable[circle.name] = circle.name

    def _exit_agent_name(self, circle: Circle) -> str:
        name = f"{circle.name}{EXIT_AGENT_SUFFIX}"
        if name in self.by_name:
            self._fail(
                join(self._circle_pointer(name), "name"),
                f"circle 名 '{name}' は circle '{circle.name}' の flow.exit のために"
                "生成する判定エージェント名と衝突します",
                f"'{name}' を rename するか、circle '{circle.name}' を rename してください",
            )
        return name

    def _assign_import_names(self) -> None:
        """`module:callable` → ローカル名。衝突したときだけモジュール修飾の別名にする。

        要件書 §3.2 の `from research.tools import web_search, fetch_page, publish` の
        形を既定にする。別名を出すのは**実際にぶつかったときだけ**なので、
        素直な `.jin` の生成物は要件書の見た目のままになる。
        """
        taken = set(_RESERVED_NAMES) | set(self.variable.values())
        refs: list[str] = []
        for circle in self.model.circles:
            for tool in circle.tools:
                if isinstance(tool, ToolFunction) and tool.ref not in refs:
                    refs.append(tool.ref)
            for guard in circle.boundary.guards if circle.boundary else []:
                if guard.ref not in refs:
                    refs.append(guard.ref)
        for ref in refs:
            module, _, name = ref.partition(":")
            if not module or not name:
                continue  # 形式エラーは _check_refs_and_builtins が既に落としている
            local = name if name not in taken else _module_alias(ref)
            suffix = 2
            while local in taken:
                local = f"{_module_alias(ref)}_{suffix}"
                suffix += 1
            taken.add(local)
            self.local_name[ref] = local
            self.import_order.append(ref)

    # -- 依存順 -----------------------------------------------------------------------
    def _dependencies(self, circle: Circle) -> list[str]:
        """その circle の定義が先に必要とする circle 名（配列順・重複なし）。"""
        names: list[str] = []
        for tool in circle.tools:
            if isinstance(tool, ToolSummon) and tool.circle in self.by_name:
                names.append(tool.circle)
        for target in circle.delegate:
            if target in self.by_name:
                names.append(target)
        for step in circle.flow.steps if circle.flow else []:
            if step in self.by_name:
                names.append(step)
        return list(dict.fromkeys(names))

    def _definition_order(self) -> list[Circle]:
        """定義が使用より先に来る順（JIN012 が閉路を落としているので必ず作れる）。

        同順位は `circles[]` の配列順で割る（決定性）。
        """
        ordered: list[Circle] = []
        state: dict[str, int] = {}  # 0=訪問中 / 1=確定

        def visit(name: str) -> None:
            if state.get(name) == 1:
                return
            if state.get(name) == 0:
                # JIN012 が落としているはずの閉路。ここへ来たら意味検査を飛ばして
                # 呼ばれている。無限再帰にせず、後ろ向き辺として打ち切る。
                return
            state[name] = 0
            for dependency in self._dependencies(self.by_name[name]):
                visit(dependency)
            state[name] = 1
            ordered.append(self.by_name[name])

        for circle in self.model.circles:
            visit(circle.name)
        return ordered

    # -- 式の組み立て -------------------------------------------------------------------
    def _tool_expression(self, circle: Circle, tool: object) -> str:
        awaited = set(circle.boundary.await_) if circle.boundary else set()
        if isinstance(tool, ToolFunction):
            local = self.local_name.get(tool.ref, tool.ref)
            wrapper = "LongRunningFunctionTool" if tool.name in awaited else "FunctionTool"
            return f"{wrapper}({local})"
        if isinstance(tool, ToolBuiltin):
            return tool.builtin
        if isinstance(tool, ToolSummon):
            return f"AgentTool(agent={self.variable.get(tool.circle, tool.circle)})"
        raise AssertionError(f"未知の tool kind: {tool!r}")  # pragma: no cover

    def _guard_arguments(self, circle: Circle) -> list[tuple[str, str]]:
        """`guards[].on` → コールバック引数。同種が複数ならリストで渡す（要件書 §3.3）。"""
        grouped: dict[str, list[str]] = {}
        for guard in circle.boundary.guards if circle.boundary else []:
            grouped.setdefault(guard.on, []).append(self.local_name.get(guard.ref, guard.ref))
        arguments: list[tuple[str, str]] = []
        for on, locals_ in grouped.items():
            value = locals_[0] if len(locals_) == 1 else "[" + ", ".join(locals_) + "]"
            arguments.append((f"{on}_callback", value))
        return arguments

    def _record_pointers(self, circle: Circle) -> None:
        base = self._circle_pointer(circle.name)
        name = circle.name
        self.pointers.agents[name] = base
        if circle.core is not None:
            self.pointers.cores[name] = join(base, "core")
        for i, tool in enumerate(circle.tools):
            self.pointers.tools.setdefault(name, {})[tool.name] = join(join(base, "tools"), i)
        for i, target in enumerate(circle.delegate):
            self.pointers.delegates.setdefault(name, {})[target] = join(join(base, "delegate"), i)
        for i, guard in enumerate(circle.boundary.guards if circle.boundary else []):
            pointer = join(join(join(base, "boundary"), "guards"), i)
            self.pointers.guards.setdefault(name, {}).setdefault(guard.on, []).append(pointer)

    def _agent_block(self, circle: Circle) -> str:
        variable = self.variable[circle.name]
        base = self._circle_pointer(circle.name)
        arguments: list[tuple[str, str]] = [("name", _py_string(circle.name))]

        if circle.core is not None:
            class_name = "LlmAgent"
            arguments.append(("model", _py_string(circle.core)))
        else:
            assert circle.flow is not None  # JIN022 が両方欠落を落としている
            class_name = {
                "sequence": "SequentialAgent",
                "parallel": "ParallelAgent",
                "loop": "LoopAgent",
            }[circle.flow.kind]

        if circle.description is not None:
            arguments.append(("description", _py_string(circle.description)))
        if circle.instruction is not None:
            arguments.append(("instruction", _py_string(circle.instruction.rune)))
        if circle.tools:
            items = [self._tool_expression(circle, tool) for tool in circle.tools]
            arguments.append(("tools", _py_list(items)))

        sub_agents: list[str] = []
        if circle.flow is not None:
            sub_agents += [self.variable.get(step, step) for step in circle.flow.steps]
            if circle.flow.exit is not None:
                exit_name = self._exit_agent_name(circle)
                self.pointers.exits[exit_name] = join(join(base, "flow"), "exit")
                self.pointers.agents[exit_name] = base
                sub_agents.append(
                    f"StateCheckAgent(\n"
                    f"            name={_py_string(exit_name)},\n"
                    f"            state_key={_py_string(circle.flow.exit.key)},\n"
                    f"            expected={_py_literal(circle.flow.exit.equals)},\n"
                    f"        )"
                )
        sub_agents += [self.variable.get(target, target) for target in circle.delegate]
        if sub_agents:
            arguments.append(("sub_agents", _py_list(sub_agents)))

        arguments += self._guard_arguments(circle)

        for state in circle.state:
            if state.out:
                arguments.append(("output_key", _py_string(state.name)))
                break

        if circle.flow is not None and circle.flow.max is not None:
            # 実測: `LoopAgent` の引数名は `max_iterations`。`max` は存在しない。
            arguments.append(("max_iterations", str(circle.flow.max)))

        body = "".join(f"    {key}={value},\n" for key, value in arguments)
        return f"{variable} = {class_name}(\n{body})\n"

    # -- 生成 -------------------------------------------------------------------------
    def generate(self) -> GeneratedProject:
        self._check_names()
        self._assign_variables()
        for circle in self.model.circles:
            self._check_circle_shape(circle)
            self._check_refs_and_builtins(circle)
        self._assign_import_names()

        if self.model.root not in self.by_name:
            # JIN060。`jin build` は check を先に通すのでここへは来ないが、
            # ライブラリとして直接呼ばれたときに黙って壊れた生成物を出さない。
            self._fail(
                "/root",
                f"root が指す circle '{self.model.root}' がありません",
                "root に circles[] のいずれかの name を書いてください",
            )
        if self.issues:
            raise CompileError(self.issues)

        ordered = self._definition_order()
        for circle in ordered:
            self._record_pointers(circle)
        blocks = [self._agent_block(circle) for circle in ordered]

        if self.issues:  # 判定エージェント名の衝突は _agent_block で出る
            raise CompileError(self.issues)

        agent_py = self._render_module(ordered, blocks)
        return GeneratedProject(
            root_name=self.model.root,
            agent_py=agent_py,
            init_py=f'{HEADER}\nfrom .agent import root_agent\n\n__all__ = ["root_agent"]\n',
            env_example=_render_env_example(),
            pointer_map=self.pointers,
        )

    def _render_module(self, ordered: list[Circle], blocks: list[str]) -> str:
        needs_exit = any(c.flow is not None and c.flow.exit is not None for c in ordered)
        agent_classes = sorted(
            {
                "LlmAgent" if c.core is not None else _WORKFLOW_CLASS[c.flow.kind]  # type: ignore[union-attr]
                for c in ordered
            }
            | ({"BaseAgent"} if needs_exit else set())
        )
        tool_names = sorted(
            {
                expression.split("(", 1)[0] if "(" in expression else expression
                for circle in ordered
                for expression in (self._tool_expression(circle, t) for t in circle.tools)
            }
        )
        adk_tools = sorted(
            n for n in tool_names if n in {"FunctionTool", "LongRunningFunctionTool"}
        )
        adk_tools += sorted(n for n in tool_names if n in BUILTIN_TOOLS)
        needs_agent_tool = "AgentTool" in tool_names

        sections: list[str] = [HEADER]

        stdlib: list[str] = []
        if needs_exit:
            stdlib.append("from collections.abc import AsyncGenerator")
            stdlib.append("from typing import Any")
        if stdlib:
            sections.append("\n".join(stdlib))

        adk: list[str] = [f"from google.adk.agents import {', '.join(agent_classes)}"]
        if needs_exit:
            adk.append("from google.adk.agents.invocation_context import InvocationContext")
            adk.append("from google.adk.events import Event, EventActions")
        if adk_tools:
            adk.append(f"from google.adk.tools import {', '.join(adk_tools)}")
        if needs_agent_tool:
            adk.append("from google.adk.tools.agent_tool import AgentTool")
        sections.append("\n".join(adk))

        user_imports = _render_user_imports(self.import_order, self.local_name)
        if user_imports:
            sections.append(user_imports)

        # 代入文どうしは 1 行空け（要件書 §3.2 の見た目）、クラス定義の前後だけ
        # PEP 8 どおり 2 行空ける。生成物は人が読むものなので体裁を崩さない。
        if needs_exit:
            sections.append("\n" + _STATE_CHECK_AGENT.rstrip("\n") + "\n")

        sections += [block.rstrip("\n") for block in blocks]
        return "\n\n".join(sections) + "\n"


#: `flow.kind` → workflow agent のクラス名（実測で存在を確認済み）。
_WORKFLOW_CLASS = {
    "sequence": "SequentialAgent",
    "parallel": "ParallelAgent",
    "loop": "LoopAgent",
}


def _py_literal(value: bool | float | str) -> str:
    """`flow.exit.equals` を Python のリテラルにする。

    `bool` は `int` の派生なので**先に**見る（`True` が `1` になると比較が変わる）。
    """
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, str):
        return _py_string(value)
    return repr(value)


def _py_list(items: list[str]) -> str:
    """複数要素は 1 行 1 要素で並べる（差分が読みやすく、順序が目で追える）。"""
    if not items:
        return "[]"
    body = "".join(f"        {item},\n" for item in items)
    return f"[\n{body}    ]"


def _render_user_imports(order: list[str], local_name: dict[str, str]) -> str:
    """`ref` の import 文をモジュールごとにまとめる（要件書 §3.2 の形）。

    モジュールは first-appearance 順、その中の名前も first-appearance 順。
    別名が付いたものだけ `as` を書く。
    """
    grouped: dict[str, list[str]] = {}
    for ref in order:
        module, _, name = ref.partition(":")
        local = local_name[ref]
        clause = name if local == name else f"{name} as {local}"
        grouped.setdefault(module, [])
        if clause not in grouped[module]:
            grouped[module].append(clause)
    return "\n".join(
        f"from {module} import {', '.join(names)}" for module, names in grouped.items()
    )


def _render_env_example() -> str:
    """`<out>/.env.example`（要件書 §3.1）。

    キー名の根拠（DP-COMMON-15「実装 Stage 1 の実測に委ねる」）は
    `delivery/20260904-1445-jin/decision-conformance.md` §2.13。google-adk 2.8.0 の
    `google/adk/cli/cli_create.py` が `adk create` で書き出す `.env` と、
    `google/genai/_api_client.py` が実際に読む環境変数を実測して決めた。**推測していない。**

    値は入れない。`.env.example` は雛形であり、秘密を書き込む先ではない。
    """
    return (
        "# generated by jin — do not edit\n"
        "#\n"
        "# このファイルを .env にコピーして値を入れてください。\n"
        "# adk は <out>/<root_name> から上へ辿って最初に見つけた .env を読みます\n"
        "# （google-adk 2.8.0 / google/adk/cli/utils/envs.py の実測）。\n"
        "# **.env は秘密を含みます。リポジトリにコミットしないでください。**\n"
        "\n"
        "# 1 = Vertex AI（GOOGLE_CLOUD_PROJECT と GOOGLE_CLOUD_LOCATION を使う）\n"
        "# 0 = Gemini API（GOOGLE_API_KEY を使う）\n"
        "GOOGLE_GENAI_USE_ENTERPRISE=0\n"
        "\n"
        "# GOOGLE_GENAI_USE_ENTERPRISE=0 のとき\n"
        "GOOGLE_API_KEY=\n"
        "\n"
        "# GOOGLE_GENAI_USE_ENTERPRISE=1 のとき\n"
        "GOOGLE_CLOUD_PROJECT=\n"
        "GOOGLE_CLOUD_LOCATION=\n"
    )


def generate(model: JinFile) -> GeneratedProject:
    """意味モデルから ADK プロジェクトのソースを作る。

    ADK に写せない構造があれば `CompileError` を投げる（**黙って落とさない**・NFR-FAIL-001）。
    """
    return _Generator(model).generate()


__all__ = [
    "BUILTIN_TOOLS",
    "EXIT_AGENT_SUFFIX",
    "HEADER",
    "ROOT_VARIABLE",
    "GeneratedProject",
    "generate",
]
