"""`jin_adk.build.write_project`: 生成物を `<out>/<root_name>/` へ安全に書き出す。

design.yaml Phase 2 machine 条件 3（ディレクトリ構造が要件書 §3.1 と一致）と、
security: 既存ファイルを黙って上書きしない / `<out>` の外へ書かない / シンボリックリンクを辿らない。
"""

from __future__ import annotations

import os
import stat
from pathlib import Path

import pytest
from jin_adk.build import TMP_SUFFIX, WriteRefused, write_project
from jin_adk.codegen import GeneratedProject, generate
from jin_core.check import check_file
from jin_core.model import JinFile

REPO_ROOT = Path(__file__).resolve().parents[3]
EXAMPLES = REPO_ROOT / "examples"


def project(name: str = "researcher") -> GeneratedProject:
    result = check_file(EXAMPLES / name / f"{name}.jin")
    assert result.model is not None
    return generate(result.model, source_name=f"{name}.jin")


def test_layout_matches_requirements_section_3_1(tmp_path: Path) -> None:
    out = tmp_path / "out"
    written = write_project(project(), out)
    assert sorted(p.relative_to(out).as_posix() for p in written) == [
        ".env.example",
        "Researcher/__init__.py",
        "Researcher/agent.py",
    ]
    assert (
        (out / "Researcher" / "__init__.py")
        .read_text(encoding="utf-8")
        .startswith("# generated by jin")
    )
    assert "root_agent" in (out / "Researcher" / "agent.py").read_text(encoding="utf-8")
    assert "GOOGLE_API_KEY" in (out / ".env.example").read_text(encoding="utf-8")


def test_written_files_keep_lf_and_follow_the_umask(tmp_path: Path) -> None:
    out = tmp_path / "out"
    write_project(project("pipeline"), out)
    raw = (out / "Pipeline" / "agent.py").read_bytes()
    assert b"\r\n" not in raw
    current_umask = os.umask(0)
    os.umask(current_umask)
    mode = stat.S_IMODE((out / "Pipeline" / "agent.py").stat().st_mode)
    assert mode == 0o644 & ~current_umask


def test_refuses_to_overwrite_existing_files_without_force(tmp_path: Path) -> None:
    out = tmp_path / "out"
    write_project(project(), out)
    (out / "Researcher" / "agent.py").write_text("hand edited\n", encoding="utf-8")
    with pytest.raises(WriteRefused) as info:
        write_project(project(), out)
    assert "--force" in str(info.value)
    assert (out / "Researcher" / "agent.py").read_text(encoding="utf-8") == "hand edited\n"


def test_refuses_when_only_env_example_exists_and_leaves_nothing_behind(tmp_path: Path) -> None:
    """パッケージディレクトリが無くても `<out>/.env.example` が既存なら拒む（ファイル単位の O_EXCL）。

    拒んだときは、今作ったパッケージディレクトリと開きかけのファイルを残さない。
    """
    out = tmp_path / "out"
    out.mkdir()
    (out / ".env.example").write_text("GOOGLE_API_KEY=mine\n", encoding="utf-8")
    with pytest.raises(WriteRefused) as info:
        write_project(project(), out)
    assert ".env.example" in str(info.value) and "--force" in str(info.value)
    assert (out / ".env.example").read_text(encoding="utf-8") == "GOOGLE_API_KEY=mine\n"
    assert not (out / "Researcher").exists()
    assert sorted(p.name for p in out.iterdir()) == [".env.example"]


def test_force_overwrites_the_three_generated_files(tmp_path: Path) -> None:
    out = tmp_path / "out"
    write_project(project(), out)
    (out / "Researcher" / "agent.py").write_text("hand edited\n", encoding="utf-8")
    write_project(project(), out, force=True)
    assert "root_agent" in (out / "Researcher" / "agent.py").read_text(encoding="utf-8")


def test_refuses_when_the_package_directory_is_a_symlink(tmp_path: Path) -> None:
    """`<out>/<root_name>` がリンクなら、その先（`<out>` の外）へ書き抜けてしまう。"""
    out = tmp_path / "out"
    elsewhere = tmp_path / "elsewhere"
    out.mkdir()
    elsewhere.mkdir()
    (out / "Researcher").symlink_to(elsewhere, target_is_directory=True)
    with pytest.raises(WriteRefused):
        write_project(project(), out, force=True)
    assert list(elsewhere.iterdir()) == []


def test_refuses_to_write_through_a_symlinked_file_even_with_force(tmp_path: Path) -> None:
    out = tmp_path / "out"
    victim = tmp_path / "victim.py"
    victim.write_text("keep\n", encoding="utf-8")
    (out / "Researcher").mkdir(parents=True)
    (out / "Researcher" / "agent.py").symlink_to(victim)
    with pytest.raises(WriteRefused):
        write_project(project(), out, force=True)
    assert victim.read_text(encoding="utf-8") == "keep\n"


def test_force_does_not_truncate_existing_files_when_a_later_file_is_refused(
    tmp_path: Path,
) -> None:
    """`--force` で 3 つ目（`.env.example` がリンク）に拒まれても、前の 2 つは open 時点で切り詰められない。

    `O_TRUNC` で開くと open した瞬間に中身が消え、拒否後に 0 バイトのファイルが残る（Phase 1 の V-1 と同型）。
    一時ファイル（`.<name>.jin-tmp`）も残さない。
    """
    out = tmp_path / "out"
    write_project(project(), out)
    init_before = (out / "Researcher" / "__init__.py").read_bytes()
    agent_before = (out / "Researcher" / "agent.py").read_bytes()
    victim = tmp_path / "victim"
    victim.write_text("keep\n", encoding="utf-8")
    (out / ".env.example").unlink()
    (out / ".env.example").symlink_to(victim)
    with pytest.raises(WriteRefused):
        write_project(project(), out, force=True)
    assert (out / "Researcher" / "__init__.py").read_bytes() == init_before
    assert (out / "Researcher" / "agent.py").read_bytes() == agent_before
    assert victim.read_text(encoding="utf-8") == "keep\n"
    assert not list(out.rglob(f"*{TMP_SUFFIX}"))


def test_force_write_failure_keeps_the_existing_files_intact(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """F-S-P2-104: `--force` で 2 回目の `os.write` が ENOSPC で失敗しても、既存 3 ファイルは 1 バイトも変わらない。

    `ftruncate` してから書く方式では `agent.py` が 0 バイトで残った（reviewer の実測）。
    一時ファイルに書いて `os.replace` で差し替えるので、書き込みの失敗は既存に届かない。残骸も残さない。
    """
    out = tmp_path / "out"
    write_project(project(), out)
    files = [
        out / "Researcher" / "__init__.py",
        out / "Researcher" / "agent.py",
        out / ".env.example",
    ]
    for path in files:
        # 再生成と同じ内容だと「差し替えられた」ことが見えない（変異 BUILD-replace-early が緑のままだった）
        path.write_text("hand edited\n", encoding="utf-8")
    before = {path: path.read_bytes() for path in files}
    calls = 0
    real_write = os.write

    def flaky(fd: int, data: object) -> int:
        nonlocal calls
        calls += 1
        if calls == 2:
            raise OSError(28, "No space left on device")
        return real_write(fd, data)  # type: ignore[arg-type]

    monkeypatch.setattr(os, "write", flaky)
    with pytest.raises(WriteRefused) as info:
        write_project(project(), out, force=True)
    assert "No space left" in str(info.value)
    for path, content in before.items():
        assert path.read_bytes() == content, path
    assert not list(out.rglob(f"*{TMP_SUFFIX}"))


def test_force_succeeds_by_replacing_through_a_temporary_file(tmp_path: Path) -> None:
    """`--force` の正常系: 一時ファイルは差し替えられて残らず、3 ファイルとも新しい内容になる。"""
    out = tmp_path / "out"
    write_project(project(), out)
    for path in (out / "Researcher" / "agent.py", out / ".env.example"):
        path.write_text("hand edited\n", encoding="utf-8")
    written = write_project(project(), out, force=True)
    assert len(written) == 3
    assert "hand edited" not in (out / "Researcher" / "agent.py").read_text(encoding="utf-8")
    assert "hand edited" not in (out / ".env.example").read_text(encoding="utf-8")
    assert not list(out.rglob(f"*{TMP_SUFFIX}"))


def test_force_keeps_the_existing_file_mode_F_S_P2_204_F_C_P2_201(tmp_path: Path) -> None:
    """F-S-P2-204 = F-C-P2-201: `--force` の差し替えは既存ファイルのモードを引き継ぐ
    （利用者が `chmod 600` した `agent.py` を umask の既定 0644 に戻さない。旧 `ftruncate` 方式と同じ挙動）。"""
    out = tmp_path / "out"
    write_project(project(), out)
    agent = out / "Researcher" / "agent.py"
    agent.chmod(0o600)
    (out / ".env.example").chmod(0o640)
    write_project(project(), out, force=True)
    assert stat.S_IMODE(agent.stat().st_mode) == 0o600
    assert stat.S_IMODE((out / ".env.example").stat().st_mode) == 0o640


def test_fchmod_failure_on_the_temporary_file_leaves_no_leftover(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """F-S-P2-301（ラウンド 3 の F-S-P2-204 修正が持ち込んだ）: tmp への `os.fchmod` が失敗しても
    `.<name>.jin-tmp` と fd を残さず `WriteRefused` にする（次の `--force` が「残骸」で拒まれない）。既存は無傷。"""
    out = tmp_path / "out"
    write_project(project(), out)
    before = {p: p.read_bytes() for p in out.rglob("*") if p.is_file()}

    def denied(fd: int, mode: int) -> None:
        raise PermissionError(1, "Operation not permitted")

    monkeypatch.setattr(os, "fchmod", denied)
    with pytest.raises(WriteRefused) as info:
        write_project(project(), out, force=True)
    assert "引き継げません" in str(info.value)
    assert not list(out.rglob(f"*{TMP_SUFFIX}")), "一時ファイルの残骸が残っている"
    for path, content in before.items():
        assert path.read_bytes() == content, path
    monkeypatch.undo()
    write_project(project(), out, force=True)  # 残骸が無いので次の --force は通る


def test_partial_apply_on_replace_failure_is_named_in_the_message(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """F-S-P2-203: 3 つ目の `os.replace` が失敗すると部分適用になる（原子性は追求しない）。
    どれが新しくどれが前のままかを文で言い、`jin build --force` の再実行を促す。`agent.py` は最後に差し替える。"""
    out = tmp_path / "out"
    write_project(project(), out)
    for path in (
        out / "Researcher" / "agent.py",
        out / "Researcher" / "__init__.py",
        out / ".env.example",
    ):
        path.write_text("old\n", encoding="utf-8")
    calls = 0
    real_replace = os.replace

    def flaky(*args, **kwargs):
        nonlocal calls
        calls += 1
        if calls == 3:
            raise PermissionError(13, "Permission denied")
        return real_replace(*args, **kwargs)

    monkeypatch.setattr(os, "replace", flaky)
    with pytest.raises(WriteRefused) as info:
        write_project(project(), out, force=True)
    message = str(info.value)
    assert "部分適用" in message and "jin build --force" in message
    assert "agent.py は前の内容のまま" in message
    # agent.py は最後なので前のまま、先の 2 つは新しい
    assert (out / "Researcher" / "agent.py").read_text(encoding="utf-8") == "old\n"
    assert (out / ".env.example").read_text(encoding="utf-8") != "old\n"
    assert not list(out.rglob(f"*{TMP_SUFFIX}"))


def test_leftover_temporary_file_is_refused_not_overwritten(tmp_path: Path) -> None:
    """前回の残骸 `.agent.py.jin-tmp` があれば `--force` でも拒む（黙って上書きしない）。"""
    out = tmp_path / "out"
    write_project(project(), out)
    leftover = out / "Researcher" / f".agent.py{TMP_SUFFIX}"
    leftover.write_text("leftover\n", encoding="utf-8")
    with pytest.raises(WriteRefused) as info:
        write_project(project(), out, force=True)
    assert "残っています" in str(info.value)
    assert leftover.read_text(encoding="utf-8") == "leftover\n"


def forged(root_name: str = "Researcher", **override: str) -> GeneratedProject:
    good = project()
    return GeneratedProject(
        root_name=root_name,
        agent_py=override.get("agent_py", good.agent_py),
        init_py=override.get("init_py", good.init_py),
        env_example=override.get("env_example", good.env_example),
        pointers=good.pointers,
    )


def test_unencodable_content_is_refused_before_any_file_is_touched(tmp_path: Path) -> None:
    """F-S-P2-005: 孤立サロゲート（不正 UTF-8 のファイル名由来）は encode を **open より前**に済ませて拒む。
    `--force` でも既存の生成物は 1 バイトも変わらず、新規なら 0 バイトのファイルを残さない。"""
    out = tmp_path / "out"
    with pytest.raises(WriteRefused) as info:
        write_project(forged(agent_py="# bad \udcff\n"), out)
    assert "UTF-8" in str(info.value)
    assert not (out / "Researcher").exists() and not (out / ".env.example").exists()

    write_project(project(), out)
    before = (out / "Researcher" / "agent.py").read_bytes()
    with pytest.raises(WriteRefused):
        write_project(forged(agent_py="# bad \udcff\n"), out, force=True)
    assert (out / "Researcher" / "agent.py").read_bytes() == before


def test_write_failure_after_open_cleans_up_only_what_it_created(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """F-C-P2-020: `os.write` の失敗（ENOSPC 等）でも作りかけを残さない（`WriteRefused` 以外の経路）。"""
    out = tmp_path / "out"

    def full_disk(fd: int, data: object) -> int:
        raise OSError(28, "No space left on device")

    monkeypatch.setattr(os, "write", full_disk)
    with pytest.raises(WriteRefused) as info:
        write_project(project(), out)
    assert "No space left" in str(info.value)
    assert not (out / "Researcher").exists() and not (out / ".env.example").exists()


def test_out_that_is_a_regular_file_is_refused_without_a_traceback(tmp_path: Path) -> None:
    """F-S-P2-004: `--out` が通常ファイル / dangling symlink でもトレースバックにしない。"""
    regular = tmp_path / "regfile"
    regular.write_text("x", encoding="utf-8")
    with pytest.raises(WriteRefused):
        write_project(project(), regular)
    dangling = tmp_path / "dangling"
    dangling.symlink_to(tmp_path / "nonexistent")
    with pytest.raises(WriteRefused):
        write_project(project(), dangling)


def test_out_itself_is_not_followed_when_it_is_a_symlink(tmp_path: Path) -> None:
    """F-S-P2-007: `<out>` 自体もリンクなら拒む（`<out>/<root>` / `--trace` と同じ規律）。"""
    elsewhere = tmp_path / "elsewhere"
    elsewhere.mkdir()
    link = tmp_path / "linkout"
    link.symlink_to(elsewhere, target_is_directory=True)
    with pytest.raises(WriteRefused) as info:
        write_project(project(), link)
    assert "シンボリックリンク" in str(info.value)
    assert list(elsewhere.iterdir()) == []


def test_over_long_root_name_is_refused_not_a_traceback(tmp_path: Path) -> None:
    """ENAMETOOLONG（非 ASCII 86 文字以上）を `WriteRefused` に包む。`out/` の残骸も作らない。"""
    out = tmp_path / "out"
    with pytest.raises(WriteRefused):
        write_project(forged(root_name="あ" * 100), out)
    assert not out.exists() or list(out.iterdir()) == []


@pytest.mark.parametrize(
    "bad",
    ["../escape", "a/b", "a\\b", "..", ".", "Re searcher", "class", "ｒｏｏｔ＿ａｇｅｎｔ"],
)
def test_root_name_is_validated_again_before_touching_the_filesystem(
    tmp_path: Path, bad: str
) -> None:
    """`root_name` は Ident（制御文字のみ禁止）なので、codegen の検査を迂回した値にも耐える。"""
    good = project()
    forged = GeneratedProject(
        root_name=bad,
        agent_py=good.agent_py,
        init_py=good.init_py,
        env_example=good.env_example,
        pointers=good.pointers,
    )
    out = tmp_path / "out"
    with pytest.raises(WriteRefused):
        write_project(forged, out)
    assert not (tmp_path / "escape").exists()
    assert not out.exists() or list(out.iterdir()) == []


def test_out_directory_is_created_when_missing(tmp_path: Path) -> None:
    out = tmp_path / "deep" / "er" / "out"
    write_project(project(), out)
    assert (out / "Researcher" / "agent.py").is_file()


def test_partial_failure_leaves_no_half_written_project(tmp_path: Path) -> None:
    """2 つ目のファイルで拒まれたとき、1 つ目だけが書かれた状態を残さない（黙って中途半端にしない）。"""
    out = tmp_path / "out"
    (out / "Researcher").mkdir(parents=True)
    (out / "Researcher" / "agent.py").write_text("existing\n", encoding="utf-8")
    with pytest.raises(WriteRefused):
        write_project(project(), out)
    assert not (out / "Researcher" / "__init__.py").exists()
    assert not (out / ".env.example").exists()


def test_model_with_invalid_structure_is_not_written(tmp_path: Path) -> None:
    """generate が BuildError を出す入力は、ファイルを 1 つも作らない（呼び出し側の責務も含めて確認）。"""
    from jin_adk.codegen import BuildError

    model = JinFile.model_validate(
        {
            "$schema": "https://xtone.internal/jin/schemas/jin.schema.json",
            "version": 1,
            "root": "class",
            "circles": [{"name": "class", "core": "m"}],
        }
    )
    with pytest.raises(BuildError):
        generate(model)
    assert not (tmp_path / "class").exists()
