"""`jin_adk.codegen`: 意味モデル → 生成コード（agent.py / __init__.py / .env.example）+ pointer 対応表。

要件書 §9「コード生成」: 生成 `agent.py` のスナップショット。
design.yaml Phase 2 machine 条件 1 / 3 / 8 をここで固定する。
"""

from __future__ import annotations

import ast
import json
import unicodedata
from pathlib import Path

import pytest
from jin_adk.codegen import (
    RESERVED_NAMES,
    BuildError,
    GeneratedProject,
    PointerMap,
    adk_template_conflicts,
    generate,
    py_literal,
)
from jin_core.check import check_file
from jin_core.model import JinFile
from jin_core.pointer import resolve_pointer

REPO_ROOT = Path(__file__).resolve().parents[3]
EXAMPLES = REPO_ROOT / "examples"
BUILD_ERROR_FIXTURES = REPO_ROOT / "tests" / "fixtures" / "build-errors"


def load(path: Path) -> JinFile:
    result = check_file(path)
    assert result.ok, [d.code for d in result.diagnostics]
    assert result.model is not None
    return result.model


def minimal(**circle: object) -> JinFile:
    """1 circle の最小モデル。`circle` で上書きする。"""
    base: dict[str, object] = {"name": "Root", "core": "gemini-2.5-flash"}
    base.update(circle)
    return JinFile.model_validate(
        {
            "$schema": "https://xtone.internal/jin/schemas/jin.schema.json",
            "version": 1,
            "root": str(base["name"]),
            "circles": [base],
        }
    )


# --------------------------------------------------------------------------------------
# machine 条件 1: 生成 agent.py のスナップショット（examples 2 本）
# --------------------------------------------------------------------------------------
@pytest.mark.parametrize("name", ["researcher", "pipeline"])
def test_generated_agent_py_snapshot(name: str, snapshot) -> None:
    """syrupy のスナップショット。`__snapshots__/` に保存され、変わると赤になる。"""
    project = generate(load(EXAMPLES / name / f"{name}.jin"), source_name=f"{name}.jin")
    assert project.agent_py == snapshot


@pytest.mark.parametrize("name", ["researcher", "pipeline"])
def test_generated_code_is_valid_python(name: str) -> None:
    project = generate(load(EXAMPLES / name / f"{name}.jin"))
    ast.parse(project.agent_py)
    ast.parse(project.init_py)


def test_generation_is_deterministic_within_a_process() -> None:
    model = load(EXAMPLES / "pipeline" / "pipeline.jin")
    assert generate(model).agent_py == generate(model).agent_py


# --------------------------------------------------------------------------------------
# 生成物の形（要件書 §3.1 / §3.2 / ADR-008 / ADR-009）
# --------------------------------------------------------------------------------------
def test_init_py_exports_root_agent() -> None:
    project = generate(load(EXAMPLES / "researcher" / "researcher.jin"))
    assert "from .agent import root_agent" in project.init_py


def test_generated_code_does_not_import_jin(tmp_path: Path) -> None:
    """ADR-008 constraint: 生成された agent.py は jin パッケージを一切 import しない。"""
    for name in ("researcher", "pipeline"):
        project = generate(load(EXAMPLES / name / f"{name}.jin"))
        for node in ast.walk(ast.parse(project.agent_py)):
            if isinstance(node, ast.ImportFrom):
                assert not (node.module or "").startswith("jin"), node.module
            if isinstance(node, ast.Import):
                assert not any(alias.name.startswith("jin") for alias in node.names)


def test_generated_code_does_not_mention_fake_llm() -> None:
    """ADR-008 constraint: FakeLlm は生成物に現れない（jin_adk 側にだけ置く）。"""
    for name in ("researcher", "pipeline"):
        project = generate(load(EXAMPLES / name / f"{name}.jin"))
        assert "FakeLlm" not in project.agent_py


def test_header_states_regeneration_and_pointer_limits() -> None:
    """ADR-008 / ADR-009 の condition: 再生成が必要な旨と、単体 adk run では pointer が付かない旨をヘッダに。"""
    project = generate(load(EXAMPLES / "pipeline" / "pipeline.jin"))
    head = project.agent_py.split("\n\n", 1)[0]
    assert head.startswith("# generated by jin")
    assert "do not edit" in head
    assert "# source:" not in head  # source_name を渡していない
    with_source = generate(load(EXAMPLES / "pipeline" / "pipeline.jin"), source_name="pipeline.jin")
    assert '# source: "pipeline.jin"\n' in with_source.agent_py  # py_literal を通した引用符付き
    # ADR-008: StateCheckAgent はコピーであり、jin 側の変更は反映されない → 再生成が必要
    state_check_lines = [line for line in head.splitlines() if "StateCheckAgent" in line]
    assert state_check_lines, head
    claim = "\n".join(head.splitlines())
    assert "反映されない" in claim and "`jin build` で再生成すること" in claim
    # ADR-009: 単体 adk run では pointer が付かない
    assert "`adk run`" in claim and "pointer は付かない" in claim


def test_state_check_agent_is_embedded_once_and_instantiated_per_loop() -> None:
    """ADR-008 の condition「StateCheckAgent 重複の扱い」: クラス定義は 1 回、ループごとにインスタンス化。"""
    model = JinFile.model_validate(
        {
            "$schema": "https://xtone.internal/jin/schemas/jin.schema.json",
            "version": 1,
            "root": "Top",
            "circles": [
                {"name": "Top", "flow": {"kind": "sequence", "steps": ["L1", "L2"]}},
                {
                    "name": "L1",
                    "flow": {"kind": "loop", "steps": ["A"], "exit": {"key": "ok", "equals": True}},
                },
                {
                    "name": "L2",
                    "flow": {"kind": "loop", "steps": ["B"], "exit": {"key": "n", "equals": 3}},
                },
                {"name": "A", "core": "m", "state": [{"name": "ok", "type": "bool", "out": True}]},
                {"name": "B", "core": "m", "state": [{"name": "n", "type": "int", "out": True}]},
            ],
        }
    )
    project = generate(model)
    assert project.agent_py.count("class StateCheckAgent(") == 1
    assert project.agent_py.count("= StateCheckAgent(") == 2
    assert project.pointers.exit_checkers == {"L1_exit_check": "L1", "L2_exit_check": "L2"}


def test_no_state_check_agent_when_no_loop_has_exit() -> None:
    project = generate(load(EXAMPLES / "researcher" / "researcher.jin"))
    assert "class StateCheckAgent" not in project.agent_py
    assert "= StateCheckAgent(" not in project.agent_py


def test_agents_are_emitted_in_dependency_order() -> None:
    """参照先（steps / delegate / summon）は参照元より先に定義される（Python の評価順）。"""
    project = generate(load(EXAMPLES / "pipeline" / "pipeline.jin"))
    order = [
        node.targets[0].id
        for node in ast.parse(project.agent_py).body
        if isinstance(node, ast.Assign) and isinstance(node.targets[0], ast.Name)
    ]
    assert order.index("Drafter") < order.index("root_agent")
    assert order.index("Critic") < order.index("Refine") < order.index("root_agent")
    assert order[-1] == "root_agent"


# --------------------------------------------------------------------------------------
# ADR-009: pointer 対応表（生成物とは別に保持し、生成物には埋め込まない）
# --------------------------------------------------------------------------------------
def test_pointer_map_covers_every_agent_tool_and_delegate() -> None:
    project = generate(load(EXAMPLES / "researcher" / "researcher.jin"))
    table = project.pointers
    assert table.root == "Researcher"
    researcher = table.agents["Researcher"]
    assert researcher.pointer == "/circles/0"
    assert researcher.core == "/circles/0/core"
    assert researcher.model == "gemini-2.5-flash"
    assert researcher.tools == (
        "/circles/0/tools/0",
        "/circles/0/tools/1",
        "/circles/0/tools/2",
        "/circles/0/tools/3",
    )
    assert table.agents["Summarizer"].pointer == "/circles/1"


def test_pointer_map_records_delegate_and_exit_pointers() -> None:
    model = JinFile.model_validate(
        {
            "$schema": "https://xtone.internal/jin/schemas/jin.schema.json",
            "version": 1,
            "root": "Boss",
            "circles": [
                {"name": "Boss", "core": "m", "delegate": ["Worker"]},
                {
                    "name": "Worker",
                    "core": "m",
                    "state": [{"name": "done", "type": "bool", "out": True}],
                },
                {
                    "name": "Loop",
                    "flow": {
                        "kind": "loop",
                        "steps": ["Solo"],
                        "max": 2,
                        "exit": {"key": "x", "equals": "y"},
                    },
                },
                {"name": "Solo", "core": "m", "state": [{"name": "x", "type": "str", "out": True}]},
            ],
        }
    )
    table = generate(model).pointers
    assert table.agents["Boss"].delegate == {"Worker": "/circles/0/delegate/0"}
    assert table.agents["Loop"].exit == "/circles/2/flow/exit"
    assert table.agents["Loop"].core is None
    assert table.exit_checkers == {"Loop_exit_check": "Loop"}


def test_every_pointer_in_the_map_resolves_in_the_model() -> None:
    """machine 条件 7 の生成側: 対応表の pointer は全部モデルに解決できる。"""
    for name in ("researcher", "pipeline"):
        model = load(EXAMPLES / name / f"{name}.jin")
        document = json.loads(model.model_dump_json(by_alias=True, exclude_defaults=True))
        for pointer in generate(model).pointers.all_pointers():
            resolve_pointer(document, pointer)


def test_pointer_map_roundtrips_through_json() -> None:
    table = generate(load(EXAMPLES / "pipeline" / "pipeline.jin")).pointers
    assert PointerMap.from_json(table.to_json()) == table


def test_pointer_map_is_not_embedded_in_the_generated_code() -> None:
    """ADR-009 constraint: 対応表を agent.py に埋め込まない。"""
    project = generate(load(EXAMPLES / "researcher" / "researcher.jin"))
    assert "/circles/" not in project.agent_py


# --------------------------------------------------------------------------------------
# security (1): .jin 由来の文字列は Python 式へエスケープなしに流れない
# --------------------------------------------------------------------------------------
NASTY = [
    'a"b',
    "a'b",
    'a"""b',
    "a\\nb",
    "line1\nline2\n",
    "\ttab\r\n",
    '") ; import os ; os.system("id") #',
    "{findings} と {{literal}} と \\u0000",
    "日本語 🐍    ",
    "",
    "a\u2028b\u2029c",
    "bad\udcff.jin",  # surrogateescape されたファイル名（F-S-P2-005）
]


@pytest.mark.parametrize("text", NASTY)
def test_py_literal_roundtrips(text: str) -> None:
    literal = py_literal(text)
    assert literal.startswith('"') and literal.endswith('"')
    assert "\n" not in literal and "\r" not in literal
    assert ast.literal_eval(literal) == text
    literal.encode("utf-8")  # 生成物を UTF-8 で書ける（孤立サロゲートが生で残らない）
    assert "\u2028" not in literal and "\u2029" not in literal


def _body_kinds(agent_py: str) -> set[str]:
    return {type(node).__name__ for node in ast.parse(agent_py).body}


@pytest.mark.parametrize(
    "source_name",
    [
        "x\nimport os; os.system('id')\n#.jin",  # F-S-P2-001 の実測入力
        'x"\nimport os\n#.jin',
        "a\u2028import os\u2029#.jin",
        "bad\udcff.jin",
    ],
)
def test_source_name_cannot_inject_statements(source_name: str) -> None:
    """`.jin` のファイル名（`source_name`）はヘッダのコメントに載る。改行入りでも文にならない。"""
    project = generate(load(EXAMPLES / "pipeline" / "pipeline.jin"), source_name=source_name)
    allowed = {"ImportFrom", "Import", "Assign", "FunctionDef", "ClassDef"}
    assert _body_kinds(project.agent_py) <= allowed
    project.agent_py.encode("utf-8")
    head = project.agent_py.split("\n\n", 1)[0]
    assert all(line.startswith("#") for line in head.splitlines())
    code_lines = [line for line in project.agent_py.splitlines() if not line.startswith("#")]
    assert "os.system" not in "\n".join(code_lines)


def test_jin_strings_cannot_inject_statements() -> None:
    """name / description / rune / equals に Python を仕込んでも、生成物は代入と import だけで構成される。"""
    injected = '") ; import os ; os.system("id") #'
    model = minimal(
        description=injected,
        instruction={"rune": f"{injected}\n{injected}"},
        state=[{"name": "k", "type": "str", "out": True}],
    )
    project = generate(model, source_name="x\nimport os\n#.jin")
    module = ast.parse(project.agent_py)
    kinds = {type(node).__name__ for node in module.body}
    assert kinds <= {"ImportFrom", "Assign"}, kinds
    assert all(
        isinstance(node, ast.ImportFrom) or isinstance(node.value, ast.Call) for node in module.body
    )
    # description がそのまま値として残っている（文として実行されていない）
    call = next(node.value for node in module.body if isinstance(node, ast.Assign))
    values = {kw.arg: kw.value for kw in call.keywords}
    assert ast.literal_eval(values["description"]) == injected


def test_equals_of_every_json_type_is_rendered_as_a_python_literal() -> None:
    for equals in (True, False, 0, -7, 2.5, "yes", '") or True #'):
        model = JinFile.model_validate(
            {
                "$schema": "https://xtone.internal/jin/schemas/jin.schema.json",
                "version": 1,
                "root": "L",
                "circles": [
                    {
                        "name": "L",
                        "flow": {
                            "kind": "loop",
                            "steps": ["A"],
                            "exit": {"key": "k", "equals": equals},
                        },
                    },
                    {
                        "name": "A",
                        "core": "m",
                        "state": [{"name": "k", "type": "any", "out": True}],
                    },
                ],
            }
        )
        project = generate(model)
        module = ast.parse(project.agent_py)
        checker = next(
            node.value
            for node in module.body
            if isinstance(node, ast.Assign)
            and isinstance(node.value, ast.Call)
            and getattr(node.value.func, "id", "") == "StateCheckAgent"
        )
        rendered = {kw.arg: kw.value for kw in checker.keywords}["expected"]
        value = ast.literal_eval(rendered)
        assert value == equals and type(value) is type(equals)


# --------------------------------------------------------------------------------------
# NFR-FAIL-001: ADK に対応物のない Jin 構造はコンパイル時エラー（黙って落とさない）
# --------------------------------------------------------------------------------------
def build_error_fixtures() -> list[Path]:
    return sorted(BUILD_ERROR_FIXTURES.glob("*.jin"))


#: fixture 名 → エラー文言に含まれるべき語（「何が悪いか」が名指しされていることの固定）。
#: `.jin` は JSON なのでコメントを書けず、期待値はここに持つ。
EXPECTED_PHRASE: dict[str, str] = {
    "adk_tool_name_duplicate": "同じツール名 'run'",
    "await_on_summon": "LongRunningFunctionTool",
    "builtin_is_a_class": "google.adk.tools",
    "builtin_name_collision": "builtin ツール 'google_search'",
    "builtin_unknown": "google.adk.tools",
    "circle_name_keyword": "予約語",
    "circle_name_not_identifier": "識別子",
    "circle_name_not_nfkc": "NFKC",
    "circle_name_user": "user",
    "exit_checker_name_collision": "_exit_check",
    "flow_circle_with_delegate": "delegate",
    "flow_circle_with_instruction": "instruction",
    "flow_circle_with_model_guard": "before_model",
    "flow_circle_with_out_state": "output_key",
    "flow_circle_with_tools": "tools",
    "ref_malformed": "module.path:callable",
    "reserved_name_collision": "衝突",
    "root_has_parent": "flow.steps に現れています",
    "rune_adk_template_conflict": "{{",
    "two_out_states": "out: true",
}


def test_every_build_error_fixture_has_an_expected_phrase() -> None:
    assert {p.stem for p in build_error_fixtures()} == set(EXPECTED_PHRASE)


@pytest.mark.parametrize("path", build_error_fixtures(), ids=lambda p: p.stem)
def test_build_error_fixture_passes_jin_check_but_fails_to_generate(path: Path) -> None:
    """fixture は `jin check` を通る（診断コードを増やさない）が、`generate` は BuildError で落ちる。

    エラーの文言は「何が悪いか + どう直すか」（hint）を含む。
    """
    result = check_file(path)
    assert result.ok, f"{path.name} は jin check を通るべき: {[d.code for d in result.diagnostics]}"
    assert result.model is not None
    with pytest.raises(BuildError) as info:
        generate(result.model)
    error = info.value
    assert error.pointer.startswith("/"), error.pointer
    assert error.hint, "hint が無い（どう直すかを伝えること）"
    assert EXPECTED_PHRASE[path.stem] in str(error), (EXPECTED_PHRASE[path.stem], str(error))


def test_build_error_pointer_resolves_in_the_fixture_model() -> None:
    for path in build_error_fixtures():
        result = check_file(path)
        assert result.model is not None
        try:
            generate(result.model)
        except BuildError as error:
            document = json.loads(
                result.model.model_dump_json(by_alias=True, exclude_defaults=True)
            )
            resolve_pointer(document, error.pointer)
        else:  # pragma: no cover - 上のテストが落とす
            pytest.fail(path.name)


def test_python_keyword_circle_name_is_rejected() -> None:
    """`"class".isidentifier()` は True で ADK も通すが、生成コードは SyntaxError になる。"""
    with pytest.raises(BuildError) as info:
        generate(minimal(name="class"))
    assert "予約語" in str(info.value)


@pytest.mark.parametrize(
    "name", ["LlmAgent", "root_agent", "str", "isinstance", "ValueError", "json"]
)
def test_reserved_generated_name_is_rejected(name: str) -> None:
    """F-S-P2-103: 生成コードの名前だけでなく、テンプレートが使う**組み込み名**も circle 名にできない。"""
    with pytest.raises(BuildError) as info:
        generate(minimal(name=name))
    assert "衝突" in str(info.value)


def _free_names(node: ast.AST) -> set[str]:
    """関数 / クラスの中で参照される名前のうち、その中で束縛されない（外側に解決される）もの。"""
    bound: set[str] = set()
    loads: set[str] = set()
    for sub in ast.walk(node):
        if isinstance(sub, ast.Name):
            (loads if isinstance(sub.ctx, ast.Load) else bound).add(sub.id)
        elif isinstance(sub, ast.arg):
            bound.add(sub.arg)
        elif isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            bound.add(sub.name)
    return loads - bound


def test_reserved_names_cover_every_free_name_the_template_uses() -> None:
    """F-S-P2-103: テンプレート由来の関数 / クラスが外側に解決する名前（組み込み名を含む）は
    すべて `RESERVED_NAMES` にある。列挙を手で保つのではなく、生成物の AST から機械で突き合わせる。
    対象は `has_exit` のときだけ描画される `_state_matches` / `StateCheckAgent`（pipeline は loop の exit を持つ）。
    """
    code = generate(load(EXAMPLES / "pipeline" / "pipeline.jin")).agent_py
    free: set[str] = set()
    definitions = [
        n for n in ast.parse(code).body if isinstance(n, (ast.FunctionDef, ast.ClassDef))
    ]
    assert {n.name for n in definitions} == {"_state_matches", "StateCheckAgent"}
    for node in definitions:
        free |= _free_names(node)
    assert {"isinstance", "str", "ValueError", "json", "BaseAgent"} <= free  # 検査が空でない
    assert free <= RESERVED_NAMES, f"RESERVED_NAMES に無い名前: {sorted(free - RESERVED_NAMES)}"


def test_exit_checker_name_collision_is_rejected() -> None:
    model = JinFile.model_validate(
        {
            "$schema": "https://xtone.internal/jin/schemas/jin.schema.json",
            "version": 1,
            "root": "L",
            "circles": [
                {
                    "name": "L",
                    "flow": {
                        "kind": "loop",
                        "steps": ["A", "L_exit_check"],
                        "exit": {"key": "k", "equals": True},
                    },
                },
                {"name": "A", "core": "m", "state": [{"name": "k", "type": "bool", "out": True}]},
                {"name": "L_exit_check", "core": "m"},
            ],
        }
    )
    with pytest.raises(BuildError) as info:
        generate(model)
    assert "L_exit_check" in str(info.value)


def two_circles(first: dict, second: dict) -> JinFile:
    return JinFile.model_validate(
        {
            "$schema": "https://xtone.internal/jin/schemas/jin.schema.json",
            "version": 1,
            "root": "A",
            "circles": [{"name": "A", "core": "m", **first}, {"name": "B", "core": "m", **second}],
        }
    )


def test_same_callable_name_in_one_circle_is_a_build_error() -> None:
    """F-C-P2-002: import は別名にできても `FunctionTool.name == func.__name__` は同じになり、
    ADK 2.8.0 は警告だけで後勝ちにする（片方が呼べない）。生成せずに落とす。"""
    model = minimal(
        tools=[
            {"name": "a", "kind": "tool", "ref": "pkg_a.tools:run"},
            {"name": "b", "kind": "tool", "ref": "pkg_b.tools:run"},
        ]
    )
    with pytest.raises(BuildError) as info:
        generate(model)
    assert info.value.pointer == "/circles/0/tools/1"
    assert "同じツール名 'run'" in str(info.value) and "別名の関数" in info.value.hint


def test_same_callable_name_in_different_circles_gets_aliased() -> None:
    """別 circle なら ADK のツール名は衝突しない。import だけ別名になる。"""
    model = two_circles(
        {"tools": [{"name": "t", "kind": "tool", "ref": "pkg_a.tools:run"}]},
        {"tools": [{"name": "t", "kind": "tool", "ref": "pkg_b.tools:run"}]},
    )
    code = generate(model).agent_py
    assert "from pkg_a.tools import run as pkg_a_tools__run" in code
    assert "from pkg_b.tools import run as pkg_b_tools__run" in code


def test_builtin_and_callable_with_the_same_adk_name_in_one_circle_is_a_build_error() -> None:
    """ADK ツール名は kind ごとに違う所から来る（tool: callable 名 / builtin: 名 / summon: circle 名）。"""
    model = minimal(
        tools=[
            {"name": "a", "kind": "tool", "ref": "mytools:google_search"},
            {"name": "b", "kind": "builtin", "builtin": "google_search"},
        ]
    )
    with pytest.raises(BuildError) as info:
        generate(model)
    assert info.value.pointer == "/circles/0/tools/1"


def test_ref_named_like_a_builtin_in_another_circle_is_aliased_not_shadowed() -> None:
    """F-C-P2-001: `from google.adk.tools import google_search` を `from mytools import google_search` が
    上書きしない（builtin 名を taken に入れて別名化する）。"""
    model = two_circles(
        {"tools": [{"name": "s", "kind": "builtin", "builtin": "google_search"}]},
        {"tools": [{"name": "t", "kind": "tool", "ref": "mytools:google_search"}]},
    )
    code = generate(model).agent_py
    assert "from google.adk.tools import FunctionTool, google_search" in code
    assert "from mytools import google_search as mytools__google_search" in code
    assert "FunctionTool(mytools__google_search)" in code
    assert "tools=[\n        google_search,\n" in code


def test_circle_named_like_a_builtin_is_rejected() -> None:
    """F-C-P2-003 / F-V-P2-011: `google_search = LlmAgent(...)` が import を上書きし、tools が agent を指す。"""
    model = JinFile.model_validate(
        {
            "$schema": "https://xtone.internal/jin/schemas/jin.schema.json",
            "version": 1,
            "root": "A",
            "circles": [
                {
                    "name": "A",
                    "core": "m",
                    "tools": [{"name": "s", "kind": "builtin", "builtin": "google_search"}],
                },
                {"name": "google_search", "core": "m"},
            ],
        }
    )
    with pytest.raises(BuildError) as info:
        generate(model)
    assert info.value.pointer == "/circles/1/name"


@pytest.mark.parametrize("name", ["ｒｏｏｔ＿ａｇｅｎｔ", "ｊｓｏｎ", "ＬｌｍＡｇｅｎｔ", "Ａ"])
def test_non_nfkc_circle_name_is_rejected(name: str) -> None:
    """F-S-P2-002: `isidentifier()` は通るが、Python は NFKC 正規化して束縛するので予約名検査を迂回できる。"""
    assert name.isidentifier()
    with pytest.raises(BuildError) as info:
        generate(minimal(name=name))
    assert "NFKC" in str(info.value) and info.value.pointer == "/circles/0/name"


def test_generated_assignments_bind_each_name_exactly_once() -> None:
    """NFKC で同じ変数に 2 回代入される形（`root_agent` の乗っ取り）が生成物に現れない。"""
    for name in ("researcher", "pipeline"):
        model = load(EXAMPLES / name / f"{name}.jin")
        targets = [
            unicodedata.normalize("NFKC", node.targets[0].id)
            for node in ast.parse(generate(model).agent_py).body
            if isinstance(node, ast.Assign) and isinstance(node.targets[0], ast.Name)
        ]
        checkers = sum(1 for c in model.circles if c.flow is not None and c.flow.exit is not None)
        assert len(targets) == len(set(targets)) == len(model.circles) + checkers


@pytest.mark.parametrize(
    ("wrapper", "pointer"),
    [
        ({"flow": {"kind": "sequence", "steps": ["Main"]}}, "/circles/1/flow/steps/0"),
        ({"core": "m", "delegate": ["Main"]}, "/circles/1/delegate/0"),
        (
            {"core": "m", "tools": [{"name": "s", "kind": "summon", "circle": "Main"}]},
            "/circles/1/tools/0/circle",
        ),
    ],
)
def test_root_with_a_parent_is_rejected(wrapper: dict, pointer: str) -> None:
    """F-C-P2-016: root が別 circle の子になる構造は `jin check` を通るが、生成物では親が付いて使われない。"""
    model = JinFile.model_validate(
        {
            "$schema": "https://xtone.internal/jin/schemas/jin.schema.json",
            "version": 1,
            "root": "Main",
            "circles": [{"name": "Main", "core": "m"}, {"name": "W", **wrapper}],
        }
    )
    with pytest.raises(BuildError) as info:
        generate(model)
    assert info.value.pointer == pointer and "root" in str(info.value)


def test_ref_colliding_with_a_circle_name_gets_aliased() -> None:
    model = JinFile.model_validate(
        {
            "$schema": "https://xtone.internal/jin/schemas/jin.schema.json",
            "version": 1,
            "root": "Root",
            "circles": [
                {
                    "name": "Root",
                    "core": "m",
                    "tools": [{"name": "t", "kind": "tool", "ref": "mod:helper"}],
                    "delegate": ["helper"],
                },
                {"name": "helper", "core": "m"},
            ],
        }
    )
    code = generate(model).agent_py
    assert "from mod import helper as mod__helper" in code
    assert "sub_agents=[helper]" in code


def test_malformed_ref_is_rejected_before_it_reaches_an_import_statement() -> None:
    with pytest.raises(BuildError) as info:
        generate(minimal(tools=[{"name": "t", "kind": "tool", "ref": "os; import sys:x"}]))
    assert "module.path:callable" in str(info.value)


# --------------------------------------------------------------------------------------
# rune と ADK 2.8.0 のテンプレート解釈の食い違い（docs/spec/model.md §3.1・実測）
# --------------------------------------------------------------------------------------
@pytest.mark.parametrize(
    ("rune", "conflicts"),
    [
        ("{draft} をレビュー", []),
        ("A {{lit}} B", ["{{lit}}"]),
        ("{draft}}", ["{draft}}"]),
        ("{opt?}", ["{opt?}"]),
        ("{artifact.file}", ["{artifact.file}"]),
        ("{app:key}", ["{app:key}"]),
        ("{not a key}", []),
        ("{{ }}", []),
        ("{ }", []),
        ("x { y", []),
    ],
)
def test_adk_template_conflicts(rune: str, conflicts: list[str]) -> None:
    assert adk_template_conflicts(rune) == conflicts


def test_rune_with_adk_only_template_syntax_is_a_build_error() -> None:
    with pytest.raises(BuildError) as info:
        generate(minimal(instruction={"rune": "A {{lit}} B"}))
    assert "{{lit}}" in str(info.value)
    assert info.value.pointer == "/circles/0/instruction/rune"


# --------------------------------------------------------------------------------------
# .env.example（DP-COMMON-15: 実測したキーだけ・推測しない）
# --------------------------------------------------------------------------------------
def test_env_example_lists_only_measured_keys() -> None:
    project = generate(load(EXAMPLES / "researcher" / "researcher.jin"))
    keys = [
        line.split("=", 1)[0].lstrip("# ").strip()
        for line in project.env_example.splitlines()
        if "=" in line and not line.lstrip("# ").startswith(("adk", "google/", "読み手", "キー"))
    ]
    measured = {
        "GOOGLE_GENAI_USE_ENTERPRISE",
        "GOOGLE_API_KEY",
        "GOOGLE_CLOUD_PROJECT",
        "GOOGLE_CLOUD_LOCATION",
    }
    assert set(keys) == measured, keys
    assert "cli_create.py" in project.env_example  # 出典を書く


def test_generated_project_is_a_frozen_value() -> None:
    project = generate(load(EXAMPLES / "pipeline" / "pipeline.jin"))
    assert isinstance(project, GeneratedProject)
    with pytest.raises(AttributeError):
        project.agent_py = "x"  # type: ignore[misc]
