"""codegen（v2 → JIL）: スナップショット・examples の実行・決定性・fixture の意味論。

スナップショットは `__snapshots__/test_codegen.ambr`（syrupy）。生成部の形を変えたら
`uv run pytest packages/jin-wasm --snapshot-update` で更新し、**差分を読んでから**コミットする。
プレリュードは別ファイル（`prelude.lua`）なのでスナップショットには生成部だけを載せる。
"""

from __future__ import annotations

import copy
import itertools
import json
from pathlib import Path
from typing import Any

import pytest
from jin_core.check import check_file, check_text
from jin_core.v2.model import JinFileV2
from jin_wasm.codegen import CodegenError, generate, lua_number, lua_string
from jin_wasm.jil import JIL_VERSION, forbidden_uses
from jin_wasm.prelude import prelude_source
from jin_wasm.runtime import HeadlessResult, run_headless

REPO_ROOT = Path(__file__).resolve().parents[3]
EXAMPLES = REPO_ROOT / "examples-v2"
PROGRAMS = REPO_ROOT / "tests" / "fixtures" / "v2-programs"
EXAMPLE_NAMES = ("paddle", "clicker", "fib", "tetris", "othello")


def load(path: Path) -> JinFileV2:
    result = check_file(path)
    assert result.ok, [d.message for d in result.diagnostics]
    assert isinstance(result.model, JinFileV2)
    return result.model


def program_part(lua: str) -> str:
    return lua.split("\n-- program\n", 1)[1]


def run(
    name: str, *, debug: bool = True, ticks: int = 300, seed: int = 7, events=()
) -> HeadlessResult:
    path = PROGRAMS / f"{name}.jin"
    game = generate(load(path), source_name=path.name, debug=debug)
    assert forbidden_uses(game.lua) == []
    return run_headless(game.lua, game.manifest, seed=seed, ticks=ticks, events=events)


def public_series(result: HeadlessResult, key: str) -> list:
    return [
        r["output"]
        for r in result.rows
        if r["kind"] == "set"
        and r["name"] == key.split(".")[1]
        and r["circle"] == key.split(".")[0]
    ]


# ---------------------------------------------------------------- リテラル


@pytest.mark.parametrize(
    ("value", "expected"),
    [(160.0, "160.0"), (1.05, "1.05"), (0.0, "0.0"), (1e20, "1e+20"), (-2.5, "-2.5"), (3, "3.0")],
)
def test_lua_number_is_always_a_float_literal(value: float, expected: str) -> None:
    assert lua_number(value) == expected


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        ("", '""'),
        ("a", '"a"'),
        ('q"b\\', '"q\\"b\\\\"'),
        ("\n\t\x00", '"\\010\\009\\000"'),
        ("日本", '"日本"'),
    ],
)
def test_lua_string_escapes(text: str, expected: str) -> None:
    assert lua_string(text) == expected


# ---------------------------------------------------------------- スナップショット


@pytest.mark.parametrize("name", EXAMPLE_NAMES)
@pytest.mark.parametrize("debug", [True, False], ids=["debug", "release"])
def test_program_snapshot(name: str, debug: bool, snapshot) -> None:
    path = EXAMPLES / name / f"{name}.jin"
    game = generate(load(path), source_name=path.name, debug=debug)
    assert program_part(game.lua) == snapshot


@pytest.mark.parametrize("name", EXAMPLE_NAMES)
def test_game_lua_is_header_prelude_program_return(name: str) -> None:
    path = EXAMPLES / name / f"{name}.jin"
    game = generate(load(path), source_name=path.name)
    header, rest = game.lua.split("\n", 3)[:3], game.lua.split("\n", 3)[3]
    assert header == [
        "-- generated by jin — do not edit",
        f'-- source: "{path.name}"',
        f"-- jin: 2  jil: {JIL_VERSION}",
    ]
    assert rest.startswith(prelude_source())
    assert game.lua.endswith("return { boot = boot, tick = tick }\n")
    assert (
        game.manifest["jil"] == __import__("hashlib").sha256(game.lua.encode("utf-8")).hexdigest()
    )


def test_manifest_lists_namespaces_and_stage() -> None:
    path = EXAMPLES / "paddle" / "paddle.jin"
    game = generate(load(path), source_name="paddle.jin", debug=True)
    assert game.manifest["namespaces"] == ["audio", "canvas", "input", "ui"]
    assert game.manifest["stage"] == {"width": 320, "height": 180, "fps": 60, "seed": 7}
    assert game.manifest["debug"] is True and game.manifest["file"] == "paddle.jin"


def test_generation_is_deterministic() -> None:
    path = EXAMPLES / "paddle" / "paddle.jin"
    a = generate(load(path), source_name="p.jin", debug=True)
    b = generate(load(path), source_name="p.jin", debug=True)
    assert a.lua == b.lua and a.manifest == b.manifest


def test_codegen_refuses_a_model_with_errors() -> None:
    text = json.dumps(
        {
            "$schema": "https://xtone.internal/jin/schemas/jin-v2.schema.json",
            "version": 2,
            "root": "Only",
            "stage": {"width": 64, "height": 64},
            "circles": [
                {
                    "name": "Only",
                    "core": "main",
                    "rites": [
                        {"name": "main", "steps": [{"do": "set", "target": "nope", "expr": "1"}]}
                    ],
                }
            ],
        }
    )
    result = check_text(text, "bad.jin")
    assert not result.ok and result.model is not None
    with pytest.raises(CodegenError):
        generate(result.model)


# ---------------------------------------------------------------- examples の実行（設計書 §12 Phase 2 の完了条件）


@pytest.mark.parametrize("name", EXAMPLE_NAMES)
def test_examples_run_300_ticks_without_error(name: str) -> None:
    path = EXAMPLES / name / f"{name}.jin"
    for debug in (True, False):
        game = generate(load(path), source_name=path.name, debug=debug)
        assert forbidden_uses(game.lua) == []
        result = run_headless(game.lua, game.manifest, seed=7, ticks=300)
        assert result.error is None
        assert all(
            list(r) == ["seq", "tick", "circle", "kind", "name", "pointer", "input", "output"]
            for r in result.rows
        )


@pytest.mark.parametrize("name", EXAMPLE_NAMES)
def test_debug_and_release_produce_the_same_frames(name: str) -> None:
    path = EXAMPLES / name / f"{name}.jin"
    model = load(path)
    debug = run_headless(*_game(model, True), seed=7, ticks=120)
    release = run_headless(*_game(model, False), seed=7, ticks=120)
    assert release.rows == []
    assert json.dumps(release.frames) == json.dumps(debug.frames)
    assert release.public == debug.public


@pytest.mark.parametrize("name", EXAMPLE_NAMES)
def test_two_runs_are_byte_identical(name: str) -> None:
    path = EXAMPLES / name / f"{name}.jin"
    model = load(path)
    a = run_headless(*_game(model, True), seed=7, ticks=120)
    b = run_headless(*_game(model, True), seed=7, ticks=120)
    assert json.dumps(a.rows) == json.dumps(b.rows)
    assert json.dumps(a.frames) == json.dumps(b.frames)


def _game(model: JinFileV2, debug: bool):
    game = generate(model, source_name="x.jin", debug=debug)
    return game.lua, game.manifest


PADDLE_INPUT = [{"tick": 0, "kind": "key", "name": "ArrowRight", "down": True}]


def test_paddle_golden_frames(snapshot) -> None:
    """paddle の 60 tick 分の表示リスト（設計書 §10「表示リスト」のゴールデン）。右キーを押しっぱなしにする。"""
    path = EXAMPLES / "paddle" / "paddle.jin"
    result = run_headless(*_game(load(path), True), seed=7, ticks=60, events=PADDLE_INPUT)
    assert result.error is None
    text = (
        "\n".join(json.dumps(f, separators=(",", ":"), ensure_ascii=False) for f in result.frames)
        + "\n"
    )
    assert text == snapshot


def test_paddle_scores_with_the_paddle_under_the_ball() -> None:
    path = EXAMPLES / "paddle" / "paddle.jin"
    result = run_headless(*_game(load(path), True), seed=7, ticks=300, events=PADDLE_INPUT)
    assert result.public["Play.score"] >= 1
    assert any(r["kind"] == "cast" and r["name"] == "audio.tone" for r in result.rows)
    tones = [f["audio"] for f in result.frames if f["audio"]]
    assert tones and tones[0] == [["tone", 440, 50]]


def test_fib_computes_fib_20_and_finishes_at_boot() -> None:
    path = EXAMPLES / "fib" / "fib.jin"
    result = run_headless(*_game(load(path), True), seed=0, ticks=10)
    assert result.public == {"Fib.answer": 6765}
    assert result.done_tick == 0
    rite_rows = [r for r in result.rows if r["kind"] == "rite"]
    assert [(r["name"], r["input"], r["output"]) for r in rite_rows] == [
        ("main", [], None),
        ("fib", [20], 6765),
    ]


# ---------------------------------------------------------------- fixture の意味論（runtime.md §2 / §3）


def test_parallel_children_read_the_previous_ticks_published_value() -> None:
    result = run("parallel_order", ticks=5)
    assert public_series(result, "A.seenB") == [0, 1, 2, 3, 4]
    assert public_series(result, "B.seenA") == [0, 1, 2, 3, 4]
    assert result.public == {"A.a": 5, "A.seenB": 4, "B.b": 5, "B.seenA": 4}


def test_parallel_order_does_not_change_the_public_series() -> None:
    path = PROGRAMS / "parallel_order.jin"
    doc = json.loads(path.read_text(encoding="utf-8"))
    swapped = copy.deepcopy(doc)
    swapped["circles"][0]["flow"]["steps"] = ["B", "A"]
    original = check_text(json.dumps(doc), "a.jin").model
    reordered = check_text(json.dumps(swapped), "b.jin").model
    a = run_headless(*_game(original, True), seed=1, ticks=6)
    b = run_headless(*_game(reordered, True), seed=1, ticks=6)
    for key in ("A.a", "A.seenB", "B.b", "B.seenA"):
        assert public_series(a, key) == public_series(b, key), key
    assert a.public == b.public


def test_transfer_pauses_the_delegator_until_the_delegate_is_done() -> None:
    result = run("transfer", ticks=6)
    assert result.error is None
    assert result.public == {"Main.n": 4, "Sub.m": 2}
    kinds = [
        (r["tick"], r["kind"], r["circle"])
        for r in result.rows
        if r["kind"] in ("transfer", "enter", "exit")
    ]
    assert kinds == [
        (-1, "enter", "Main"),
        (1, "transfer", "Main"),
        (1, "enter", "Sub"),
        (3, "exit", "Sub"),
    ]
    # Main は tick 2 / 3 の間 tick を受けない
    main_ticks = [r["tick"] for r in result.rows if r["kind"] == "event" and r["circle"] == "Main"]
    assert main_ticks == [0, 1, 4, 5]


def test_input_text_concatenates_the_text_committed_in_the_tick() -> None:
    """abilities.md §3（v2.1）: `input.text()` はこの tick に確定した文字列を発生順につなぐ。無ければ ""。

    確定した文字列は key イベントとは別の `text` イベントで届き、押下状態（`keys` / `pointer`）には触らない。
    非 ASCII もそのまま運ばれ、`len` はコードポイントで数える。
    """
    events = [
        {"tick": 0, "kind": "text", "text": "ab"},
        {"tick": 0, "kind": "key", "name": "Backspace", "down": True},
        {"tick": 0, "kind": "text", "text": "c"},
        {"tick": 1, "kind": "key", "name": "Backspace", "down": False},
        {"tick": 2, "kind": "text", "text": "日本😀"},
    ]
    result = run("text_input", ticks=4, events=events)
    assert result.error is None
    # tick 0: "ab" と "c" をつないでから Backspace で 1 文字消す。tick 1 / 3 は何も確定していない。
    assert public_series(result, "Only.name") == ["abc", "ab", "ab日本😀"]
    assert result.public == {"Only.name": "ab日本😀", "Only.typed": 6}


def test_emit_is_delivered_on_the_next_tick() -> None:
    result = run("emit_message", ticks=3)
    assert result.public == {"Receiver.got": 42, "Receiver.text": "hi"}
    emit = next(r for r in result.rows if r["kind"] == "emit")
    assert (
        emit["tick"] == 1 and emit["input"] == [42, "hi"] and emit["output"] is True
    )  # 配達の tick に積む
    event = next(r for r in result.rows if r["kind"] == "event" and r["name"] == "message")
    assert event["tick"] == 1 and event["input"] == ["hello", 42, "hi"]
    got = next(r for r in result.rows if r["kind"] == "set" and r["name"] == "got")
    assert got["tick"] == 1


def test_key_and_pointer_events_reach_the_handlers() -> None:
    events = [
        {"tick": 1, "kind": "key", "name": "ArrowLeft", "down": True},
        {"tick": 1, "kind": "key", "name": "Space", "down": True},
        {"tick": 2, "kind": "pointer", "x": 50, "y": 9, "down": True},
        {"tick": 2, "kind": "key", "name": "Space", "down": False},
        {"tick": 3, "kind": "key", "name": "ArrowLeft", "down": False},
    ]
    result = run("key_pointer", ticks=5, events=events)
    assert result.error is None
    assert result.public == {
        "Only.keys": 2,
        "Only.held": 2,
        "Only.pressed": 1,
        "Only.lastx": 50,
        "Only.lastdown": True,
    }
    pointer_event = next(r for r in result.rows if r["kind"] == "event" and r["name"] == "pointer")
    assert pointer_event["input"] == [{"x": 50, "y": 9, "down": True}]


def test_wait_until_resumes_when_the_condition_holds() -> None:
    result = run("wait_until", ticks=10)
    assert result.done_tick == 3
    assert result.public == {"Only.n": 3, "Only.flag": True}
    waits = [(r["tick"], r["input"], r["output"]) for r in result.rows if r["kind"] == "wait"]
    assert waits == [(-1, {"until": True}, "suspend"), (3, {"until": True}, "resume")]


def test_list_effects_loops_and_pure_functions() -> None:
    result = run("each_list", ticks=1)
    assert result.error is None
    assert result.public == {
        "Only.total": 13,
        "Only.label": "4/ell",
        "Only.count": 3,
        "Only.has": True,
        "Only.second": 2,
    }
    casts = [(r["name"], r["input"]) for r in result.rows if r["kind"] == "cast"]
    assert casts == [("push", [[3, 1, 2], 4]), ("removeAt", [[3, 1, 2, 4], 0])]


def test_summon_calls_the_other_circles_rite_synchronously() -> None:
    result = run("summon", ticks=2)
    assert result.done_tick == 0
    assert result.public == {"Main.result": 42, "Lib.calls": 1}
    rite_rows = [
        (r["circle"], r["name"], r["input"], r["output"])
        for r in result.rows
        if r["kind"] == "rite"
    ]
    assert rite_rows == [("Main", "main", [], None), ("Lib", "double", [21], 42)]


def test_index_out_of_range_is_an_error_row() -> None:
    result = run("runtime_error_index", ticks=3)
    assert result.error is not None and "添字" in result.error
    assert result.done_tick == 0
    error = next(r for r in result.rows if r["kind"] == "error")
    assert error["tick"] == -1 and error["circle"] == "Only"
    assert error["pointer"] == "/circles/0/rites/0"  # 直前の行（rite）の pointer


def test_bad_color_is_an_error_row_at_the_cast() -> None:
    result = run("bad_color", ticks=3)
    assert result.error is not None and "色" in result.error
    assert result.done_tick == 0
    error = next(r for r in result.rows if r["kind"] == "error")
    assert error["pointer"] == "/circles/0/rites/1/steps/0"  # cast 行は呼び出しの前に積む


def test_guard_failure_is_an_assert_row_and_does_not_stop() -> None:
    result = run("assert_guard", ticks=4)
    asserts = [(r["tick"], r["output"]) for r in result.rows if r["kind"] == "assert"]
    assert asserts == [(1, "n は 2 未満"), (2, "n は 2 未満"), (3, "n は 2 未満")]
    assert result.public == {"Only.n": 4} and result.done_tick is None


def test_sequence_advances_and_exit_handler_runs() -> None:
    result = run("sequence_exit", ticks=5)
    assert result.done_tick == 1
    assert result.public == {"Second.n": 102}
    events = [(r["tick"], r["circle"], r["name"]) for r in result.rows if r["kind"] == "event"]
    assert events == [(0, "Second", "tick"), (1, "Second", "tick"), (1, "Second", "exit")]
    enters = [(r["tick"], r["circle"]) for r in result.rows if r["kind"] == "enter"]
    assert enters == [(-1, "First"), (-1, "Second")]


# ---------------------------------------------------------------- num は常に float（jil.md §2）


@pytest.mark.parametrize("name", ["each_list", "wait_until", "key_pointer"])
def test_num_states_are_floats_at_runtime(name: str) -> None:
    """生成部の数値リテラル・純関数・添字計算が整数サブタイプを作らないことを、実行後の state で見る。

    文字列の走査では陣の添字（`STOP(2)` など）と区別できないので、`S[i]` を返す末尾を足して
    `math.type` を読む（テスト専用の JIL。`jin build` の出力ではない）。
    """
    from jin_wasm.runtime import sandboxed_runtime

    path = PROGRAMS / f"{name}.jin"
    model = load(path)
    game = generate(model, source_name=path.name, debug=False)
    lua = game.lua.replace(
        "return { boot = boot, tick = tick }\n", "return { boot = boot, tick = tick, S = S }\n"
    )
    runtime = sandboxed_runtime()
    entry = runtime.execute(lua)
    entry.boot(0, runtime.table_from(game.manifest, recursive=True))
    for t in range(4):
        entry.tick(
            t,
            runtime.table_from(
                {"events": [], "keys": {}, "pointer": {"x": 0.0, "y": 0.0, "down": False}},
                recursive=True,
            ),
        )
    math_type = runtime.eval("math.type")
    checked = 0
    for i, circle in enumerate(model.circles, start=1):
        for j, state in enumerate(circle.state):
            if state.type != "num":
                continue
            value = entry.S[i][f"k_{j}"]
            assert math_type(value) == "float", (circle.name, state.name, value)
            checked += 1
    assert checked >= 1


# ---------------------------------------------------------------- tetris（examples-v2 の 4 本目）


def test_tetris_clears_a_full_row_and_scores(tmp_path: Path) -> None:
    """行消去: 満杯の行が消えて上の行が 1 段落ち、得点 100・行数 1 になる（板は list<num> の平らな 200 要素）。

    盤面は `begin` が毎回空にするので、写しで `init` に満杯の行（18 行目）と右端だけ空いた行（19 行目）を置き、
    `begin` の初期化を外してからハードドロップ（Space）を 1 回入れる。
    """
    doc = json.loads((EXAMPLES / "tetris" / "tetris.jin").read_text(encoding="utf-8"))
    play = doc["circles"][1]
    board = [0] * 180 + [1] * 10 + [2] * 9 + [0]
    for state in play["state"]:
        if state["name"] == "board":
            state["init"] = json.dumps(board)
    begin = next(r for r in play["rites"] if r["name"] == "begin")
    begin["steps"] = [
        s
        for s in begin["steps"]
        if not (s["do"] == "cast" and s["target"] in ("clear", "push"))
        and not (s["do"] == "loop" and s["kind"] == "count")
    ]
    path = tmp_path / "tetris-clear.jin"
    path.write_text(json.dumps(doc, ensure_ascii=False), encoding="utf-8")
    game = generate(load(path), source_name=path.name, debug=True)
    result = run_headless(
        game.lua,
        game.manifest,
        seed=3,
        ticks=12,
        events=[
            {"tick": 3, "kind": "key", "name": "Space", "down": True},
            {"tick": 4, "kind": "key", "name": "Space", "down": False},
        ],
    )
    assert result.error is None
    assert result.public["Play.score"] == 100 and result.public["Play.lines"] == 1
    assert result.public["Play.placed"] == 1
    after = result.public["Play.board"]
    assert after[190:200] == [2] * 9 + [0]  # 右端の空いた行はそのまま最下段
    assert all(v == 0 for v in after[:170])  # 満杯の行は消え、上は空のまま
    assert sum(1 for v in after[170:190] if v != 0) == 4  # 落としたミノ 4 マスが 1 段下がって載る
    assert [r["name"] for r in result.rows if r["kind"] == "rite"][:1] == ["begin"]


def test_tetris_ends_in_the_result_screen_when_pieces_pile_up() -> None:
    """何も操作しないと積み上がって Play が done になり、Result の画面（GAME OVER と 2 つのボタン）に移る。"""
    path = EXAMPLES / "tetris" / "tetris.jin"
    game = generate(load(path), source_name=path.name, debug=False)
    result = run_headless(game.lua, game.manifest, seed=3, ticks=2400)
    assert result.error is None and result.done_tick is None
    last = result.frames[-1]["ops"]
    assert ["text", "GAME OVER", 100, 8] in last
    assert [op[1] for op in last if op[0] == "button"] == ["RETRY", "QUIT"]
    assert result.public["Play.placed"] > 10


# ---------------------------------------------------------------- othello（5 本目・相手が v1 の陣 = LLM）

_OTHELLO_DIRS = ((-1, -1), (0, -1), (1, -1), (-1, 0), (1, 0), (-1, 1), (0, 1), (1, 1))


def _othello_flips(board: list[int], x: int, y: int, dx: int, dy: int, who: int) -> int:
    cx, cy, n = x + dx, y + dy, 0
    while 0 <= cx < 8 and 0 <= cy < 8 and board[cy * 8 + cx] == 3 - who:
        n, cx, cy = n + 1, cx + dx, cy + dy
    return n if n > 0 and 0 <= cx < 8 and 0 <= cy < 8 and board[cy * 8 + cx] == who else 0


def _othello_greedy(board: list[int], who: int) -> int:
    """othello.jin の内蔵 AI と同じ規則（取れる石が最多・同数なら添字の小さい方）の独立実装。"""
    best, choice = 0, -1
    for i in range(64):
        x, y = i % 8, i // 8
        if board[i] != 0:
            continue
        g = sum(_othello_flips(board, x, y, dx, dy, who) for dx, dy in _OTHELLO_DIRS)
        if g > best:
            best, choice = g, i
    return choice


def _othello_play_out() -> tuple[list[int], list[tuple[int, int]]]:
    """両者が greedy で打ち切った最終盤面と、O（AI）の手の列。"""
    board = [0] * 64
    board[27], board[28], board[35], board[36] = 2, 1, 1, 2
    turn, o_moves = 1, []

    def place(i: int, who: int) -> None:
        x, y = i % 8, i // 8
        board[i] = who
        for dx, dy in _OTHELLO_DIRS:
            for k in range(_othello_flips(board, x, y, dx, dy, who)):
                board[(y + dy * (k + 1)) * 8 + x + dx * (k + 1)] = who

    while True:
        i = _othello_greedy(board, turn)
        if turn == 2:
            o_moves.append((i % 8, i // 8))
        place(i, turn)
        if _othello_greedy(board, 3 - turn) >= 0:
            turn = 3 - turn
        elif _othello_greedy(board, turn) < 0:
            return board, o_moves


def test_othello_rules_match_an_independent_implementation() -> None:
    """記憶 auto = "1" で X も内蔵 AI が打ち、答えが読めない（fake の答え）ので O も内蔵 AI に倒れる。

    両者 greedy の対局を Python で独立に打ち切った最終盤面とバイト一致する（flips / legal / place / pass /
    終局の規則がそのまま突き合う）。v1 の陣への問いは O の手番ごとに 1 回出て、全部が内蔵 AI に倒れる。
    """
    expected, o_moves = _othello_play_out()
    path = EXAMPLES / "othello" / "othello.jin"
    game = generate(load(path), source_name=path.name, debug=True)
    asked: list[str] = []

    def fake(ask: dict[str, Any]) -> str:
        asked.append(ask["prompt"])
        return "fake-response"

    result = run_headless(
        game.lua, game.manifest, seed=5, ticks=400, storage={"auto": "1"}, answer=fake
    )
    assert result.error is None
    assert (
        result.public["Play.over"] is True
    )  # root は loop の flow（Result で RETRY / QUIT を待つ）
    assert result.public["Board.board"] == expected
    assert (result.public["Board.black"], result.public["Board.white"]) == (
        expected.count(1),
        expected.count(2),
    )
    assert result.public["Play.llmMoves"] == 0
    assert result.public["Play.fallbackMoves"] == len(o_moves) == len(asked)
    assert asked[0].startswith("You are O in Othello") and "Your legal moves: " in asked[0]
    assert "c3 " in asked[0]  # 最初の O の合法手（X が d3 に打った後）


def test_othello_reads_the_llm_answer_and_plays_it_when_legal() -> None:
    """答えの文中の座標（"I choose c3."）を読んで打つ。合法なら LLM の手、違法や無答なら内蔵 AI。

    答えを独立実装の greedy の手に揃えると盤面は同じまま `llmMoves` だけが O の手数になる。
    """
    expected, o_moves = _othello_play_out()
    path = EXAMPLES / "othello" / "othello.jin"
    game = generate(load(path), source_name=path.name, debug=False)
    moves = iter(o_moves)

    def oracle(ask: dict[str, Any]) -> str:
        x, y = next(moves)
        return f"I choose {'abcdefgh'[x]}{y + 1}."

    result = run_headless(
        game.lua, game.manifest, seed=5, ticks=400, storage={"auto": "1"}, answer=oracle
    )
    assert result.error is None and result.public["Board.board"] == expected
    assert result.public["Play.llmMoves"] == len(o_moves)
    assert result.public["Play.fallbackMoves"] == 0

    # 盤面に無い座標（z9）と読めない答えは内蔵 AI に倒れる
    answers = itertools.cycle(["z9", "pass", "I resign"])
    result = run_headless(
        game.lua,
        game.manifest,
        seed=5,
        ticks=12,
        storage={"auto": "1"},
        answer=lambda ask: next(answers),
    )
    assert result.error is None
    assert result.public["Play.llmMoves"] == 0 and result.public["Play.fallbackMoves"] >= 2


def test_othello_in_the_browser_shape_waits_then_falls_back_to_the_builtin_ai() -> None:
    """人がクリックで打ち、答えが来なければ（ブラウザ相当）60 tick 待って内蔵 AI が打つ。"""
    path = EXAMPLES / "othello" / "othello.jin"
    game = generate(load(path), source_name=path.name, debug=True)
    result = run_headless(
        game.lua,
        game.manifest,
        seed=5,
        ticks=80,
        events=[
            {"tick": 2, "kind": "pointer", "x": 64, "y": 48, "down": True},  # d3（X の合法手）
            {"tick": 3, "kind": "pointer", "x": 64, "y": 48, "down": False},
            {"tick": 20, "kind": "pointer", "x": 16, "y": 16, "down": True},  # AI の手番中は無視
            {"tick": 21, "kind": "pointer", "x": 16, "y": 16, "down": False},
        ],
        replay=True,  # 録画の再生と同じく問いに答えない（ブラウザのプレイヤーも答えない）
    )
    assert result.error is None
    assert result.public["Board.board"][19] == 1  # d3 に X
    assert result.public["Play.fallbackMoves"] == 1 and result.public["Play.llmMoves"] == 0
    asks = [r for r in result.rows if r["kind"] == "cast" and r["name"] == "rival"]
    assert len(asks) == 1
    placed = [r for r in result.rows if r["kind"] == "rite" and r["name"] == "place"]
    assert [r["tick"] for r in placed] == [
        2,
        63,
    ]  # 問いは tick 3、答えを 60 tick 待って tick 63 に打つ
    assert result.public["Play.turn"] == 1 and result.public["Board.board"][0] == 0
