"""JIL の契約（docs/spec/v2/jil.md §1 / §2）: 禁止語・グローバル・ヘッダを生成物の走査で固定する。

v1 の `guard:` 走査（`test_guard_claims.py`）と同じ手口で、**生成物そのもの**を見る。
対象はプレリュードと、examples-v2 3 本 + `tests/fixtures/v2-programs/` の全 `.jin` から
生成した `game.lua`（debug / release の両方）。
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from jin_core.check import check_file
from jin_wasm.codegen import generate
from jin_wasm.jil import (
    HOST_ENTRY_POINTS,
    HOST_HOOK_GLOBALS,
    JIL_VERSION,
    forbidden_uses,
    strip_comments_and_strings,
)
from jin_wasm.prelude import prelude_source

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCES = sorted(
    [
        *(REPO_ROOT / "examples-v2").rglob("*.jin"),
        *(REPO_ROOT / "tests/fixtures/v2-programs").glob("*.jin"),
    ]
)
IDS = [p.stem for p in SOURCES]

#: 生成部が書き換えてよいプレリュードの局所（プレリュード先頭のコメントと 1:1）。
# `JR`（型紙の読み手。resume 用）は debug だけに出る（jil.md §1・設計書 §11 #42）。
PROGRAM_ASSIGNMENTS = {"DEBUG", "ROOT", "FPS", "CIRCLES", "R", "JF", "JR"}


def games():
    for path in SOURCES:
        result = check_file(path)
        assert result.ok, path
        for debug in (True, False):
            yield path, debug, generate(result.model, source_name=path.name, debug=debug).lua


def test_there_is_something_to_scan() -> None:
    assert len(SOURCES) >= 3 + 10, IDS


def test_prelude_has_no_forbidden_words() -> None:
    assert forbidden_uses(prelude_source()) == []


@pytest.mark.parametrize("path", SOURCES, ids=IDS)
def test_generated_jil_has_no_forbidden_words(path: Path) -> None:
    result = check_file(path)
    for debug in (True, False):
        lua = generate(result.model, source_name=path.name, debug=debug).lua
        assert forbidden_uses(lua) == [], [str(u) for u in forbidden_uses(lua)]


@pytest.mark.parametrize("path", SOURCES, ids=IDS)
def test_only_boot_and_tick_are_global(path: Path) -> None:
    """jil.md §2: グローバルは boot / tick の 2 つだけ。`_ENV` への代入も無い。"""
    result = check_file(path)
    for debug in (True, False):
        raw = generate(result.model, source_name=path.name, debug=debug).lua
        lua = strip_comments_and_strings(raw)
        functions = re.findall(r"^function\s+([A-Za-z_][A-Za-z0-9_]*)", lua, re.MULTILINE)
        assert sorted(functions) == sorted(HOST_ENTRY_POINTS), functions
        # 生成部が列 0 で代入する名前はプレリュードの局所 6 つだけ（プレリュード側は `local` で宣言済み）
        program = strip_comments_and_strings(raw.split("\n-- program\n", 1)[1])
        assignments = re.findall(
            r"^([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^\]]*\]\s*)*=[^=]", program, re.MULTILINE
        )
        assert set(assignments) <= PROGRAM_ASSIGNMENTS, sorted(
            set(assignments) - PROGRAM_ASSIGNMENTS
        )
        assert "_ENV" not in lua
        # プレリュードの列 0 の代入は、先に `local` で宣言した名前への代入だけ
        prelude = strip_comments_and_strings(prelude_source())
        declared = set(
            re.findall(r"^local\s+(?:function\s+)?([A-Za-z_][A-Za-z0-9_]*)", prelude, re.MULTILINE)
        )
        for line_assign in re.findall(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=[^=]", prelude, re.MULTILINE):
            assert line_assign in declared, line_assign


def test_the_prelude_reads_only_the_two_host_hook_globals() -> None:
    """runtime.md §8: プレリュードが読むホスト提供のグローバルは `JIN_ARM` / `JIN_HOOK` だけ。

    読み込み時に `local` へ捕まえる（ホストは読んだ後に消す）。`JIN_` で始まる名前が他に
    現れないこと、捕まえた局所を `boot` / `tick` の先頭と `coroutine.resume` の前で呼ぶことを見る。
    """
    prelude = strip_comments_and_strings(prelude_source())
    captured = re.findall(
        r"^local\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(JIN_[A-Za-z0-9_]*)", prelude, re.MULTILINE
    )
    assert [g for _, g in captured] == list(HOST_HOOK_GLOBALS), captured
    assert sorted(set(re.findall(r"\bJIN_[A-Za-z0-9_]*", prelude))) == sorted(HOST_HOOK_GLOBALS)
    arm, hook = (name for name, _ in captured)
    for entry in HOST_ENTRY_POINTS:
        body = prelude.split(f"\nfunction {entry}(", 1)[1]
        assert body.lstrip().split("\n", 2)[1].strip() == f"if {arm} then {arm}() end", entry
    resumes = [m.start() for m in re.finditer(r"coroutine\.resume\(", prelude)]
    assert len(resumes) == 1, "coroutine.resume は resume() の 1 か所だけ（jil.md §2）"
    before = prelude[: resumes[0]].rsplit("\n", 2)[-2].strip()
    assert before == f"if {hook} then {hook}(co) end", before


@pytest.mark.parametrize("path", SOURCES, ids=IDS)
def test_header_names_the_source_and_the_jil_version(path: Path) -> None:
    result = check_file(path)
    lua = generate(result.model, source_name=path.name).lua
    lines = lua.split("\n", 3)
    assert lines[0] == "-- generated by jin — do not edit"
    assert lines[1] == f'-- source: "{path.name}"'
    assert lines[2] == f"-- jin: 2  jil: {JIL_VERSION}"


def test_the_prelude_does_not_use_locale_dependent_character_classes() -> None:
    """Lua の `%c` は C の `iscntrl` でプロセスのロケールに従う（v2.1 で見つけた・jil.md §2）。

    UTF-8 のロケールで動く lupa のホストでは、非 ASCII の途中のバイトが制御文字に数えられて
    `JS` が `\\u00xx` に書き換え、tick 結果の JSON が壊れた（ブラウザの Wasmoon は C ロケールなので割れない）。
    文字列を運ぶ `input.text` で表に出たので、範囲で書くことを固定する。
    """
    code = "\n".join(
        line for line in prelude_source().splitlines() if not line.lstrip().startswith("--")
    )
    assert "%c" not in code


def test_the_prelude_declares_its_jil_version() -> None:
    assert f"jil: {JIL_VERSION}" in prelude_source().split("\n", 1)[0]


def test_the_jil_spec_names_the_current_version() -> None:
    """jil.md §1 の `jil: N` はプレリュード / 生成部の版と同じ（v2.1 で 1 → 2。片方だけ変えない）。"""
    spec = (REPO_ROOT / "docs" / "spec" / "v2" / "jil.md").read_text(encoding="utf-8")
    assert f"-- jin: 2  jil: {JIL_VERSION}" in spec
    assert f"`jil: {JIL_VERSION}` は JIL の契約の版" in spec


def test_the_prelude_implements_every_catalog_namespace_and_pure_function() -> None:
    """abilities.md §1 / expr.md §4.1 の名前がプレリュードの `H` / `F` に揃っている（v2.1 で `storage` / `num`）。"""
    from jin_core.v2 import abilities
    from jin_core.v2.expr import PURE_FUNCTION_NAMES

    prelude = prelude_source()
    for ns in abilities.NAMESPACES:
        assert f"H.{ns.name} = {{" in prelude, ns.name
        block = prelude.split(f"H.{ns.name} = {{", 1)[1].split("\n}", 1)[0]
        for member in ns.members:
            # `key = function` でも `pointer = pointer_value` でも、メンバ名への代入があればよい
            assert re.search(rf'(^|\s|\[")({member.name})("\])?\s*=[^=]', block, re.MULTILINE), (
                f"H.{ns.name}.{member.name} がプレリュードに無い"
            )
    for name in PURE_FUNCTION_NAMES:
        assert re.search(rf"^F\.{name} = ", prelude, re.MULTILINE), f"F.{name} がプレリュードに無い"
