"""JIL の契約（docs/spec/v2/jil.md §1 / §2）: 禁止語・グローバル・ヘッダを生成物の走査で固定する。

v1 の `guard:` 走査（`test_guard_claims.py`）と同じ手口で、**生成物そのもの**を見る。
対象はプレリュードと、examples-v2 3 本 + `tests/fixtures/v2-programs/` の全 `.jin` から
生成した `game.lua`（debug / release の両方）。
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from jin_core.check import check_file
from jin_wasm.codegen import generate
from jin_wasm.jil import HOST_ENTRY_POINTS, JIL_VERSION, forbidden_uses, strip_comments_and_strings
from jin_wasm.prelude import prelude_source

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCES = sorted(
    [
        *(REPO_ROOT / "examples-v2").rglob("*.jin"),
        *(REPO_ROOT / "tests/fixtures/v2-programs").glob("*.jin"),
    ]
)
IDS = [p.stem for p in SOURCES]

#: 生成部が書き換えてよいプレリュードの局所（プレリュード先頭のコメントと 1:1）。
PROGRAM_ASSIGNMENTS = {"DEBUG", "ROOT", "FPS", "CIRCLES", "R", "JF"}


def games():
    for path in SOURCES:
        result = check_file(path)
        assert result.ok, path
        for debug in (True, False):
            yield path, debug, generate(result.model, source_name=path.name, debug=debug).lua


def test_there_is_something_to_scan() -> None:
    assert len(SOURCES) >= 3 + 10, IDS


def test_prelude_has_no_forbidden_words() -> None:
    assert forbidden_uses(prelude_source()) == []


@pytest.mark.parametrize("path", SOURCES, ids=IDS)
def test_generated_jil_has_no_forbidden_words(path: Path) -> None:
    result = check_file(path)
    for debug in (True, False):
        lua = generate(result.model, source_name=path.name, debug=debug).lua
        assert forbidden_uses(lua) == [], [str(u) for u in forbidden_uses(lua)]


@pytest.mark.parametrize("path", SOURCES, ids=IDS)
def test_only_boot_and_tick_are_global(path: Path) -> None:
    """jil.md §2: グローバルは boot / tick の 2 つだけ。`_ENV` への代入も無い。"""
    result = check_file(path)
    for debug in (True, False):
        raw = generate(result.model, source_name=path.name, debug=debug).lua
        lua = strip_comments_and_strings(raw)
        functions = re.findall(r"^function\s+([A-Za-z_][A-Za-z0-9_]*)", lua, re.MULTILINE)
        assert sorted(functions) == sorted(HOST_ENTRY_POINTS), functions
        # 生成部が列 0 で代入する名前はプレリュードの局所 6 つだけ（プレリュード側は `local` で宣言済み）
        program = strip_comments_and_strings(raw.split("\n-- program\n", 1)[1])
        assignments = re.findall(
            r"^([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^\]]*\]\s*)*=[^=]", program, re.MULTILINE
        )
        assert set(assignments) <= PROGRAM_ASSIGNMENTS, sorted(
            set(assignments) - PROGRAM_ASSIGNMENTS
        )
        assert "_ENV" not in lua
        # プレリュードの列 0 の代入は、先に `local` で宣言した名前への代入だけ
        prelude = strip_comments_and_strings(prelude_source())
        declared = set(
            re.findall(r"^local\s+(?:function\s+)?([A-Za-z_][A-Za-z0-9_]*)", prelude, re.MULTILINE)
        )
        for line_assign in re.findall(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=[^=]", prelude, re.MULTILINE):
            assert line_assign in declared, line_assign


@pytest.mark.parametrize("path", SOURCES, ids=IDS)
def test_header_names_the_source_and_the_jil_version(path: Path) -> None:
    result = check_file(path)
    lua = generate(result.model, source_name=path.name).lua
    lines = lua.split("\n", 3)
    assert lines[0] == "-- generated by jin — do not edit"
    assert lines[1] == f'-- source: "{path.name}"'
    assert lines[2] == f"-- jin: 2  jil: {JIL_VERSION}"


def test_the_prelude_declares_its_jil_version() -> None:
    assert f"jil: {JIL_VERSION}" in prelude_source().split("\n", 1)[0]
