"""Jin v2（`version: 2`）のドキュメントを LSP がどこまで扱うか（Phase 3 → Phase 5）。

- 診断 / `jin/model` / `jin/renderSvg`（`focus` に `陣名/手順名` を許す）/ formatting は v2 で答える（Phase 3）
- **hover / completion / `jin/applyOps` は v2 で答える**（Phase 5・設計書 §8）。`jin/model` と
  `jin/applyOps` の応答には `jil` / `manifest` が載る（ライブリロード）
- definition / references / documentSymbol / rename / codeAction は v1 だけ（設計書 §11 #36）。
  v2 のドキュメントでは「モデル無し」と同じ振る舞い（None / 空）になり、**落ちない**
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from jin_core.canonical import dumps
from jin_core.check import check_text
from jin_core.v2.model import STEP_KINDS, JinFileV2
from jin_core.v2.ops import OPERATIONS, apply_ops
from jin_lsp import requests
from jin_lsp.features import completion, edits, navigation
from jin_lsp.session import DocumentStore
from lsprotocol import types

REPO_ROOT = Path(__file__).resolve().parents[3]
PADDLE = (REPO_ROOT / "examples-v2" / "paddle" / "paddle.jin").read_text(encoding="utf-8")
URI = "file:///paddle.jin"


@pytest.fixture
def state():
    store = DocumentStore()
    return store.update(URI, PADDLE)


def position_of(needle: str, inside: str, offset: int = 1) -> types.Position:
    """`needle` を含む最初の行の、`inside` の先頭から `offset` 文字目（LSP の 0 始まり）。"""
    for index, line in enumerate(PADDLE.splitlines()):
        if needle in line:
            return types.Position(line=index, character=line.index(inside) + offset)
    raise AssertionError(f"{needle!r} を含む行が無い")


def labels(state, position: types.Position) -> list[str]:
    return [item.label for item in completion.complete(state, position).items]


def hover_text(state, position: types.Position) -> str:
    found = navigation.hover(state, position)
    assert found is not None
    return found.contents.value


# ---------------------------------------------------------------- Phase 3 の範囲


def test_a_v2_document_keeps_its_model_and_has_no_v1_model(state) -> None:
    assert isinstance(state.model, JinFileV2)
    assert state.model_v1 is None
    assert state.model_v1_for_display is None
    assert isinstance(state.model_for_display, JinFileV2)
    assert isinstance(state.model_v2_for_display, JinFileV2)
    assert state.diagnostics == []


def test_render_svg_answers_for_v2_with_a_rite_focus(state) -> None:
    result = requests.jin_render_svg(state, URI)
    assert result["svg"].startswith("<svg") and result["stale"] is False
    assert 'data-jin-kind="stage"' in result["svg"]
    rite = requests.jin_render_svg(state, URI, focus="Play/step")
    assert 'data-jin-kind="step-edge"' in rite["svg"]
    with pytest.raises(requests.RequestError) as caught:
        requests.jin_render_svg(state, URI, focus="Play/nope")
    assert caught.value.code == "JIN002"


def test_render_svg_accepts_seq_zero_traces_for_v2(state) -> None:
    rows = [{"seq": 0, "pointer": "/circles/1"}, {"seq": 1, "pointer": "/stage"}]
    result = requests.jin_render_svg(state, URI, focus="Play", trace=rows, upto=0)
    assert 'data-jin-fired="1"' in result["svg"]


def test_formatting_still_works_for_v2(state) -> None:
    assert edits.format_document(state) == []  # 既に正準形


def test_v1_only_features_answer_empty_for_v2_without_raising(state) -> None:
    position = types.Position(line=2, character=5)
    assert navigation.definition(state, URI, position) is None
    assert navigation.references(state, URI, position) == []
    assert navigation.document_symbols(state) == []
    assert edits.prepare_rename(state, position) is None
    assert edits.rename(state, URI, position, "X") is None
    params = types.CodeActionParams(
        text_document=types.TextDocumentIdentifier(uri=URI),
        range=types.Range(position, position),
        context=types.CodeActionContext(diagnostics=[]),
    )
    assert edits.code_actions(state, URI, params) == []


# ---------------------------------------------------------------- jin/model と JIL


def test_jin_model_returns_the_v2_model_with_its_jil(state) -> None:
    result = requests.jin_model(state, URI)
    assert result["model"]["version"] == 2
    assert any(p["pointer"] == "/stage/width" for p in result["pointers"])
    assert result["jilError"] is None
    assert (
        result["jil"].startswith("-- generated by jin")
        and "return { boot = boot, tick = tick }" in result["jil"]
    )
    assert result["manifest"]["file"] == "paddle.jin"
    assert result["manifest"]["debug"] is True  # 実行パネルはトレース行を使う


def test_jin_model_for_v1_has_no_jil() -> None:
    from .conftest import minimal

    v1 = DocumentStore().update("file:///a.jin", minimal())
    result = requests.jin_model(v1, "file:///a.jin")
    assert "jil" not in result and "manifest" not in result


# ---------------------------------------------------------------- jin/applyOps（v2）


def test_apply_ops_applies_a_v2_operation_and_returns_its_inverse_and_jil(state) -> None:
    op = {
        "op": "addState",
        "pointer": "/circles/1/state",
        "value": {"name": "lives", "type": "num", "init": "3"},
    }
    result = requests.jin_apply_ops(state, URI, [op])
    assert result["ok"] is True
    assert result["inverses"] == [{"op": "removeState", "pointer": "/circles/1/state/3"}]
    assert result["warnings"] == []
    assert result["model"]["circles"][1]["state"][3]["name"] == "lives"
    # テキストは正準形（保存と `jin fmt` がバイト一致する・要件書 成功条件 5）
    assert result["text"] == dumps(JinFileV2.model_validate(result["model"]))
    assert check_text(result["text"], "m.jin").ok
    # ライブリロード用の JIL（addState は生成部に現れる）
    assert result["jilError"] is None and '"lives"' in result["jil"]


def test_apply_ops_keeps_ok_when_the_expression_is_broken_but_reports_no_jil(state) -> None:
    """ops.md §1: 式の構文 / 型エラーはオペレーションの失敗にしない。JIL だけが作れない。"""
    op = {"op": "setStep", "pointer": "/circles/1/rites/0/steps/0", "value": {"expr": "nope +"}}
    result = requests.jin_apply_ops(state, URI, [op])
    assert result["ok"] is True
    assert result["jil"] is None and result["manifest"] is None
    assert "JIN201" in result["jilError"]


def test_apply_ops_reports_a_v2_failure_with_a_code(state) -> None:
    result = requests.jin_apply_ops(state, URI, [{"op": "removeCircle", "pointer": "/circles/9"}])
    assert result["ok"] is False
    assert result["error"]["code"] == "JIN002"
    assert result["error"]["pointer"] == "/circles/9"


@pytest.mark.parametrize("name", sorted(OPERATIONS))
def test_every_v2_operation_name_is_reachable_through_apply_ops(state, name: str) -> None:
    """未知のオペレーションと同じ経路（JIN002・`未知のオペレーション`）に落ちないこと。

    引数不足で失敗してもよい（それは各オペレーションの検査）。32 件が `jin_core.v2.ops.OPERATIONS`
    経由で呼ばれていることだけを見る。
    """
    result = requests.jin_apply_ops(state, URI, [{"op": name, "pointer": "/nope"}])
    assert result["ok"] is False
    assert "未知のオペレーション" not in result["error"]["message"]


def test_apply_ops_matches_jin_core_v2_ops_byte_for_byte(state) -> None:
    ops = [
        {"op": "rename", "pointer": "/circles/1/state/2", "value": "points"},
        {"op": "addStep", "pointer": "/circles/1/rites/0/steps", "value": {"do": "finish"}},
    ]
    result = requests.jin_apply_ops(state, URI, ops)
    expected = apply_ops(state.model, ops)
    assert result["text"] == dumps(expected.model)
    assert result["inverses"] == expected.inverses


# ---------------------------------------------------------------- hover（v2・設計書 §8）


def test_hover_on_an_expression_shows_its_type(state) -> None:
    text = hover_text(state, position_of('"init": "Ball{', '"Ball{'))
    assert "**式**" in text and "`Ball`" in text
    text = hover_text(state, position_of('"exit"', '"Result.'))
    assert "`Result.quit`" in text and "`bool`" in text


def test_hover_on_a_host_sigil_lists_the_catalog_signatures(state) -> None:
    text = hover_text(state, position_of('"host": "canvas"', '"canvas"'))
    assert "`canvas.rect(x: num, y: num, w: num, h: num)`" in text
    text = hover_text(state, position_of('"target": "canvas.rect"', '"canvas.rect"'))
    assert text.startswith("**ホスト能力** `canvas.rect(")


def test_hover_on_a_state_says_whether_it_is_public(state) -> None:
    text = hover_text(state, position_of('"name": "score"', '"score"'))
    assert "**公開**" in text and "`Play.score`" in text
    text = hover_text(state, position_of('"name": "ball"', '"ball"'))
    assert "**非公開**" in text


def test_hover_on_a_rite_and_an_on_handler(state) -> None:
    assert hover_text(state, position_of('"name": "step"', '"step"')).startswith(
        "**手順 `step(dt: num)`**"
    )
    text = hover_text(state, position_of('"event": "tick"', '"tick"'))
    assert "手順 `step`" in text and "`(num)`" in text


# ---------------------------------------------------------------- completion（v2・設計書 §8）


def test_completion_in_an_expression_lists_identifiers_in_scope_order(state) -> None:
    found = labels(state, position_of('"expr": "ball.x + ball.vx * dt"', '"ball.x'))
    # 局所 → state → sigil（点付き）→ 他の陣の公開 state（点付き）→ 型紙 → 純関数
    assert found.index("dt") < found.index("ball") < found.index("input.key")
    assert found.index("input.key") < found.index("Result.quit") < found.index("Ball")
    assert found.index("Ball") < found.index("abs")
    assert "canvas.rect" not in found  # 戻り値の無いメンバは式に書けない（expr.md §3.3）


def test_completion_after_a_dot_lists_only_the_members(state) -> None:
    assert labels(state, position_of('"expr": "ball.x + ball.vx * dt"', "ball.x", 5)) == [
        "x",
        "y",
        "vx",
        "vy",
    ]
    assert labels(state, position_of('"target": "canvas.rect"', "canvas.rect", 7)) == [
        "clear",
        "ink",
        "rect",
        "circle",
        "line",
        "text",
        "sprite",
    ]
    assert labels(state, position_of('"exit"', '"Result.', 8)) == ["quit"]


def test_completion_for_a_cast_target_lists_rites_sigils_and_effects(state) -> None:
    found = labels(state, position_of('"target": "canvas.rect"', '"canvas.rect"'))
    assert found[:4] == ["begin", "serve", "step", "paint"]
    assert "canvas.rect" in found and "push" in found


def test_completion_offers_the_step_kinds_for_do(state) -> None:
    assert labels(state, position_of('"do": "set"', '"set"')) == list(STEP_KINDS)


def test_completion_offers_type_names(state) -> None:
    found = labels(state, position_of('"type": "num"', '"num"'))
    assert found[:5] == ["num", "bool", "str", "Pointer", "Ball"]
    assert "list<Ball>" in found


def test_completion_offers_reference_names_and_keys(state) -> None:
    assert labels(state, position_of('"core": "begin"', '"begin"')) == [
        "begin",
        "serve",
        "step",
        "paint",
    ]
    assert labels(state, position_of('"host": "canvas"', '"canvas"'))[:2] == ["canvas", "input"]
    assert labels(state, position_of('"event": "tick"', '"tick"')) == [
        "tick",
        "key",
        "pointer",
        "message",
        "exit",
    ]
    assert labels(state, position_of('"width"', '"width"')) == [
        "width",
        "height",
        "fps",
        "seed",
        "assets",
    ]


def test_completion_in_a_constant_init_offers_only_forms_and_pure_functions(state) -> None:
    found = labels(state, position_of('"init": "Ball{', '"Ball{'))
    assert found[:2] == ["Pointer", "Ball"] and "abs" in found
    assert "ball" not in found and "input.key" not in found


def test_completion_in_flow_exit_offers_only_public_state(state) -> None:
    assert labels(state, position_of('"exit"', '"Result.')) == ["Play.score", "Result.quit"]


def test_completion_survives_a_syntax_error_in_the_expression_being_typed() -> None:
    """打鍵途中の式（JIN201）でも、そのステップのスコープで候補を出す。"""
    broken = PADDLE.replace('"expr": "ball.x + ball.vx * dt"', '"expr": "ball.x +"', 1)
    state = DocumentStore().update(URI, broken)
    assert any(d.code == "JIN201" for d in state.diagnostics)
    line = next(i for i, l in enumerate(broken.splitlines()) if '"expr": "ball.x +"' in l)
    column = broken.splitlines()[line].index('"ball.x') + 1
    found = labels(state, types.Position(line=line, character=column))
    assert found[:2] == ["dt", "ball"]


def test_a_v2_step_added_through_apply_ops_round_trips_to_canonical_text(state) -> None:
    """§12 の完了条件「ステップを足す → 保存 → 正準形一致」の LSP 側。"""
    op = {"op": "addStep", "pointer": "/circles/1/rites/0/steps", "value": {"do": "finish"}}
    result = requests.jin_apply_ops(state, URI, [op])
    reparsed = json.loads(result["text"])
    assert reparsed["circles"][1]["rites"][0]["steps"][-1] == {"do": "finish"}
    assert dumps(JinFileV2.model_validate(reparsed)) == result["text"]


def test_hover_on_an_agent_sigil_and_its_cast_describes_the_ask(state) -> None:
    """`agent`（v1 の陣への問い・v2.1・runtime.md §11）: sigil と `cast` の hover が要求 id と答えの形を言う。"""
    text = (REPO_ROOT / "tests" / "fixtures" / "v2-programs" / "agent.jin").read_text(
        encoding="utf-8"
    )
    uri = "file:///agent.jin"
    agent_state = DocumentStore().update(uri, text)

    def at(needle: str, inside: str) -> types.Position:
        for index, line in enumerate(text.splitlines()):
            if needle in line:
                return types.Position(line=index, character=line.index(inside) + 1)
        raise AssertionError(needle)

    found = hover_text(agent_state, at('"file": "agents/oracle.jin"', '"agents/oracle.jin"'))
    assert "agent `agents/oracle.jin`" in found
    assert "`oracle(prompt: str) -> num`" in found
    assert "`on message`" in found
    found = hover_text(agent_state, at('"target": "oracle"', '"oracle"'))
    assert "agent `agents/oracle.jin`" in found
